import {
  Activity,
  AlertTriangle,
  BarChart3,
  Bell,
  BellRing,
  BriefcaseBusiness,
  Building2,
  CalendarCheck,
  CalendarDays,
  ClipboardList,
  Clock3,
  FileText,
  Gauge,
  HardDrive,
  IdCard,
  Laptop,
  Layers3,
  LogOut,
  MapPin,
  MonitorDot,
  Network,
  PieChart,
  Settings,
  ShieldCheck,
  Split,
  TimerReset,
  UserCog,
  UserPlus,
  Users,
} from 'lucide-react';
import type { NavGroup } from '@/types/navigation';

export const navigation: NavGroup[] = [
  { label: 'Dashboard', path: '/', icon: Gauge, permission: 'dashboard:view' },
  {
    label: 'Organization',
    icon: Building2,
    permission: 'organization:manage',
    children: [
      { label: 'Companies', path: '/organization/companies', icon: BriefcaseBusiness, permission: 'companies:manage', roles: ['SUPER_ADMIN'] },
      { label: 'Branches', path: '/organization/branches', icon: MapPin, permission: 'branches:view', roles: ['COMPANY_ADMIN', 'HR'] },
      { label: 'Departments', path: '/organization/departments', icon: Network, permission: 'departments:view', roles: ['COMPANY_ADMIN', 'HR'] },
      { label: 'Designations', path: '/organization/designations', icon: Layers3, permission: 'designations:view', roles: ['COMPANY_ADMIN', 'HR'] },
      { label: 'Shifts', path: '/organization/shifts', icon: Clock3, permission: 'shifts:view', roles: ['COMPANY_ADMIN', 'HR'] },
    ],
  },
  {
    label: 'Employees',
    icon: Users,
    permission: 'employees:view',
    children: [
      { label: 'Employee Directory', path: '/people/employees', icon: Users, permission: 'employees:view', roles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'HR', 'MANAGER', 'EMPLOYEE'] },
      { label: 'Employee Documents', path: '/employees/documents', icon: FileText, permission: 'employees:view', roles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'HR', 'MANAGER', 'EMPLOYEE'] },
      { label: 'Onboarding', path: '/employees/onboarding', icon: UserPlus, permission: 'employees:view', roles: ['COMPANY_ADMIN', 'HR'] },
      { label: 'Exit Management', path: '/employees/exit-management', icon: LogOut, permission: 'employees:view', roles: ['COMPANY_ADMIN', 'HR'] },
      { label: 'Assets', path: '/employees/assets', icon: HardDrive, permission: 'employees:view', roles: ['COMPANY_ADMIN', 'HR', 'MANAGER'] },
    ],
  },
  {
    label: 'Attendance',
    icon: CalendarCheck,
    permission: 'attendance:view',
    children: [
      { label: 'Attendance', path: '/attendance', icon: CalendarCheck, permission: 'attendance:view', roles: ['COMPANY_ADMIN', 'HR', 'MANAGER', 'EMPLOYEE'] },
      { label: 'Corrections', path: '/attendance/corrections', icon: ClipboardList, permission: 'attendance:view', roles: ['COMPANY_ADMIN', 'HR', 'MANAGER', 'EMPLOYEE'] },
      { label: 'Attendance Policies', path: '/attendance/policies', icon: TimerReset, permission: 'attendance:manage', roles: ['COMPANY_ADMIN', 'HR'] },
      { label: 'Break Policies', path: '/attendance/break-policies', icon: BellRing, permission: 'attendance:manage', roles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'HR'] },
      { label: 'Overtime Rules', path: '/attendance/overtime-rules', icon: Clock3, permission: 'attendance:manage', roles: ['COMPANY_ADMIN', 'HR'] },
      { label: 'Holiday Calendar', path: '/attendance/holiday-calendar', icon: CalendarDays, permission: 'attendance:manage', roles: ['COMPANY_ADMIN', 'HR'] },
    ],
  },
  {
    label: 'Leave',
    icon: FileText,
    permission: 'leave:view',
    children: [
      { label: 'Leave Requests', path: '/leave/requests', icon: Activity, permission: 'leave:view', roles: ['COMPANY_ADMIN', 'HR', 'MANAGER', 'EMPLOYEE'] },
      { label: 'Leave Types', path: '/leave/types', icon: FileText, permission: 'leave:manage', roles: ['COMPANY_ADMIN', 'HR'] },
      { label: 'Leave Balance', path: '/leave/balances', icon: ClipboardList, permission: 'leave:view', roles: ['COMPANY_ADMIN', 'HR', 'MANAGER', 'EMPLOYEE'] },
    ],
  },
  {
    label: 'Monitoring',
    icon: MonitorDot,
    permission: 'monitoring:view',
    children: [
      { label: 'Live Status', path: '/monitoring/live-status', icon: MonitorDot, permission: 'monitoring:view' },
      { label: 'Activity Timeline', path: '/monitoring/activity', icon: Activity, permission: 'monitoring:view' },
      { label: 'Screenshots', path: '/monitoring/screenshots', icon: IdCard, permission: 'monitoring:view' },
      { label: 'Apps & URLs', path: '/monitoring/apps-urls', icon: Laptop, permission: 'monitoring:view' },
      { label: 'Devices', path: '/monitoring/devices', icon: HardDrive, permission: 'monitoring:view' },
      { label: 'Idle Time', path: '/monitoring/idle-time', icon: TimerReset, permission: 'monitoring:view' },
      { label: 'Productivity', path: '/monitoring/productivity', icon: PieChart, permission: 'monitoring:view' },
      { label: 'Alerts', path: '/monitoring/alerts', icon: AlertTriangle, permission: 'monitoring:view' },
    ],
  },
  {
    label: 'Reports',
    icon: BarChart3,
    permission: 'reports:view',
    children: [
      { label: 'Attendance Reports', path: '/reports/attendance', icon: CalendarCheck, permission: 'reports:view' },
      { label: 'Employee Reports', path: '/reports/employees', icon: Users, permission: 'reports:view' },
      { label: 'Leave Reports', path: '/reports/leave', icon: FileText, permission: 'reports:view' },
      { label: 'Monitoring Reports', path: '/reports/monitoring', icon: MonitorDot, permission: 'reports:view' },
    ],
  },
  {
    label: 'Settings',
    icon: Settings,
    permission: 'settings:view',
    children: [
      { label: 'Company Profile', path: '/settings/company-profile', icon: Building2, permission: 'settings:view', roles: ['COMPANY_ADMIN', 'HR'] },
      { label: 'Users', path: '/settings/users', icon: UserCog, permission: 'people:manage', roles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'HR'] },
      { label: 'Roles', path: '/settings/roles', icon: ShieldCheck, permission: 'people:manage', roles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'HR'] },
      { label: 'Permissions', path: '/settings/permissions', icon: Split, permission: 'people:manage', roles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'HR'] },
      { label: 'Attendance Settings', path: '/settings/attendance', icon: TimerReset, permission: 'attendance:manage', roles: ['COMPANY_ADMIN', 'HR'] },
      { label: 'Desktop Agent Settings', path: '/settings/desktop-agent', icon: Laptop, permission: 'settings:view', roles: ['COMPANY_ADMIN', 'HR'] },
      { label: 'Notification Settings', path: '/settings/notifications', icon: Bell, permission: 'settings:view', roles: ['COMPANY_ADMIN', 'HR'] },
      { label: 'General Settings', path: '/settings/general', icon: Settings, permission: 'settings:view' },
    ],
  },
];
