import { Alert, Box, Button, Card, CardContent, Checkbox, FormControlLabel, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { LoadingSkeleton } from '@/components/loading-skeleton';
import { PageHeader } from '@/components/page-header';
import { PageLayout } from '@/components/page-layout';
import { getEntitlementCatalog, getPlans } from '@/features/plans/plans-api';
import { getCompanySeatUsage } from '@/features/usage-seats/usage-seats-api';
import type { AmendmentPayload, BillingInterval } from './subscription.types';
import { amendSubscription, getSubscription } from './subscriptions-api';

export default function SubscriptionAmendPage() {
  const { id } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const subscription = useQuery({ queryKey: ['subscription', id], queryFn: () => getSubscription(id!), enabled: Boolean(id) }); const plans = useQuery({ queryKey: ['plans', 'amend-options'], queryFn: () => getPlans({ page: 1, limit: 100, status: 'ACTIVE' }) }); const catalog = useQuery({ queryKey: ['entitlement-catalog'], queryFn: getEntitlementCatalog });
  const [planId, setPlanId] = useState(''); const [seats, setSeats] = useState(''); const [interval, setInterval] = useState<BillingInterval>('MONTHLY'); const [price, setPrice] = useState(''); const [entitlements, setEntitlements] = useState<string[]>([]); const [maxStorageBytes, setMaxStorageBytes] = useState(''); const [screenshotRetentionDays, setScreenshotRetentionDays] = useState(''); const [allowOverLimit, setAllowOverLimit] = useState(false); const [overrideReason, setOverrideReason] = useState(''); const [error, setError] = useState('');
  const source = subscription.data?.data; const selectedPlan = plans.data?.data.data.find((plan) => plan.id === planId); const custom = (selectedPlan?.billingModel ?? source?.billingModelSnapshot) === 'CUSTOM'; const catalogItems = useMemo(() => catalog.data?.data ?? [], [catalog.data]);
  const usage = useQuery({ queryKey: ['usage-seats', 'company', source?.companyId, { summary: true }], queryFn: () => getCompanySeatUsage(source!.companyId, { page: 1, limit: 1 }), enabled: Boolean(source?.companyId) });
  const currentUsedSeats = usage.data?.data.seats.used;
  const amendmentNeedsOverride = currentUsedSeats !== undefined && Number.isInteger(Number(seats)) && Number(seats) >= 1 && Number(seats) < currentUsedSeats;
  useEffect(() => { if (!source || planId) return; setPlanId(source.planId); setSeats(String(source.seatQuantity)); setInterval(source.billingInterval); setPrice(String((source.billingModelSnapshot === 'PER_USER' ? source.pricePerSeatMinor ?? 0 : source.customRecurringPriceMinor ?? 0) / 100)); setEntitlements(source.entitlementsSnapshot); setMaxStorageBytes(source.limitsSnapshot.maxStorageBytes?.toString() ?? ''); setScreenshotRetentionDays(source.limitsSnapshot.screenshotRetentionDays?.toString() ?? ''); }, [source, planId]);
  const mutation = useMutation({ mutationFn: (payload: AmendmentPayload) => amendSubscription(id!, payload), onSuccess: async ({ data }) => { await Promise.all([client.invalidateQueries({ queryKey: ['usage-seats'] }), client.invalidateQueries({ queryKey: ['subscriptions'] })]); navigate(`/saas/subscriptions/${data.id}`, { replace: true }); }, onError: (e: unknown) => { const candidate = e as { response?: { data?: { message?: string | string[] } } }; const message = candidate.response?.data?.message; setError(Array.isArray(message) ? message.join(', ') : message ?? 'Subscription amendment failed.'); } });
  if (subscription.isLoading || plans.isLoading) return <PageLayout><LoadingSkeleton rows={8} /></PageLayout>;
  if (!source || (source.status !== 'ACTIVE' && source.status !== 'SUSPENDED')) return <PageLayout><Alert severity="warning">Only ACTIVE or SUSPENDED subscriptions can be amended.</Alert></PageLayout>;
  const changePlan = (nextId: string) => { setPlanId(nextId); setAllowOverLimit(false); setOverrideReason(''); const plan = plans.data?.data.data.find((value) => value.id === nextId); if (!plan) return; setSeats(String(Math.max(plan.minSeats ?? 1, source.seatQuantity))); setPrice(String(((plan.billingModel === 'PER_USER' ? plan.monthlyPricePerSeatMinor : null) ?? 0) / 100)); setEntitlements(plan.entitlements); setMaxStorageBytes(plan.limits.maxStorageBytes?.toString() ?? ''); setScreenshotRetentionDays(plan.limits.screenshotRetentionDays?.toString() ?? ''); };
  const submit = () => { setError(''); const seatQuantity = Number(seats); const amount = Number(price); const limitValues = [maxStorageBytes, screenshotRetentionDays].filter(Boolean); if (!Number.isInteger(seatQuantity) || seatQuantity < 1 || !Number.isFinite(amount) || amount < 0 || limitValues.some((value) => !Number.isInteger(Number(value)) || Number(value) < 0)) { setError('Seats, effective price, and limits must be valid non-negative values.'); return; } if (usage.isLoading || usage.isError || currentUsedSeats === undefined) { setError('Current Employee seat usage must be loaded before creating the successor agreement.'); return; } if (seatQuantity < currentUsedSeats && (!allowOverLimit || !overrideReason.trim())) { setError('Acknowledge the over-limit amendment and provide a reason.'); return; } const limits: Record<string, number> = {}; if (maxStorageBytes) limits.maxStorageBytes = Number(maxStorageBytes); if (screenshotRetentionDays) limits.screenshotRetentionDays = Number(screenshotRetentionDays); const payload: AmendmentPayload = { planId, seatQuantity, billingInterval: interval, ...(custom ? { customRecurringPriceMinor: Math.round(amount * 100), entitlements, limits } : { pricePerSeatMinor: Math.round(amount * 100) }), ...(seatQuantity < currentUsedSeats ? { allowOverLimit: true, reason: overrideReason.trim() } : {}) }; mutation.mutate(payload); };
  return <PageLayout><PageHeader title="Amend Subscription" description="Create a successor agreement without rewriting historical commercial terms." breadcrumbs={['Admin', 'SaaS Management', 'Subscriptions', source.company.name, 'Amend']} />
    <Alert severity="info">The current {source.status} agreement will become SUPERSEDED atomically. Its successor will remain {source.status}; amendment never resumes suspended access.</Alert>{error ? <Alert severity="error">{error}</Alert> : null}{usage.isError ? <Alert severity="error" action={<Button color="inherit" onClick={() => void usage.refetch()}>Retry</Button>}>Current Employee seat usage could not be loaded.</Alert> : null}
    <Card><CardContent><Stack component="form" gap={3} onSubmit={(e) => { e.preventDefault(); submit(); }}><Box sx={grid}><TextField label="Company" value={source.company.name} disabled /><TextField select label="Plan" value={planId} onChange={(e) => changePlan(e.target.value)}>{!plans.data?.data.data.some((plan) => plan.id === source.planId) ? <MenuItem value={source.planId}>{source.planNameSnapshot} ({source.planCodeSnapshot}) — current agreement</MenuItem> : null}{(plans.data?.data.data ?? []).map((plan) => <MenuItem key={plan.id} value={plan.id}>{plan.name} ({plan.code})</MenuItem>)}</TextField><TextField required type="number" label="Contracted seats" value={seats} inputProps={{ min: selectedPlan?.minSeats ?? 1, max: selectedPlan?.maxSeats ?? undefined }} onChange={(e) => setSeats(e.target.value)} /><TextField select label="Billing interval" value={interval} onChange={(e) => setInterval(e.target.value as BillingInterval)}>{['MONTHLY', 'YEARLY', 'CUSTOM'].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField required type="number" label={custom ? 'Negotiated recurring price' : 'Agreed per-seat price'} value={price} inputProps={{ min: 0, step: '0.01' }} onChange={(e) => setPrice(e.target.value)} helperText={`Amount in ${selectedPlan?.currency ?? source.currency} minor-unit safe input.`} /></Box>
      {custom ? <Box><Typography fontWeight={800}>Effective entitlements</Typography><Typography variant="body2" color="text.secondary">Only currently available, assignable catalog capabilities can be included.</Typography><Stack direction="row" flexWrap="wrap" gap={1}>{catalogItems.map((item) => { const disabled = !item.assignable || item.availability !== 'AVAILABLE'; return <FormControlLabel key={item.key} disabled={disabled} control={<Checkbox checked={entitlements.includes(item.key)} onChange={(_, checked) => setEntitlements((current) => checked ? [...current, item.key] : current.filter((key) => key !== item.key))} />} label={`${item.name}${disabled ? ' — Coming Soon' : ''}`} />; })}</Stack><Typography fontWeight={800} mt={2}>Negotiated limits</Typography><Box sx={{ ...grid, mt: 1 }}><TextField type="number" label="Maximum storage (bytes)" value={maxStorageBytes} onChange={(e) => setMaxStorageBytes(e.target.value)} inputProps={{ min: 0, step: 1 }} /><TextField type="number" label="Screenshot retention (days)" value={screenshotRetentionDays} onChange={(e) => setScreenshotRetentionDays(e.target.value)} inputProps={{ min: 0, step: 1 }} /></Box></Box> : null}
      {amendmentNeedsOverride && currentUsedSeats !== undefined ? <Stack gap={1.5}><Alert severity="warning">The proposed capacity of {seats} is below current usage of {currentUsedSeats}. The successor will start {currentUsedSeats - Number(seats)} seats over limit.</Alert><FormControlLabel control={<Checkbox checked={allowOverLimit} onChange={(_, checked) => setAllowOverLimit(checked)} />} label="Allow successor capacity below current seat usage" /><TextField required label="Override reason" value={overrideReason} onChange={(event) => setOverrideReason(event.target.value)} multiline minRows={3} inputProps={{ maxLength: 500 }} helperText="Required audit reason for the intentional over-limit amendment." /></Stack> : null}
      <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="flex-end" gap={1}><Button onClick={() => navigate(`/saas/subscriptions/${source.id}`)}>Cancel</Button><Button type="submit" variant="contained" disabled={mutation.isPending}>{mutation.isPending ? 'Creating successor…' : 'Create successor agreement'}</Button></Stack></Stack></CardContent></Card>
  </PageLayout>;
}
const grid = { display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))' }, gap: 2 };
