import { Alert, Box, Button, Card, CardContent, MenuItem, Stack, TablePagination, TextField, Typography } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { RefreshCw, RotateCcw } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { EmptyState } from '@/components/empty-state';
import { EnterpriseFilterCard, EnterpriseFilterSearch } from '@/components/enterprise/filters';
import { LoadingSkeleton } from '@/components/loading-skeleton';
import { PageHeader } from '@/components/page-header';
import { PageLayout } from '@/components/page-layout';
import { StatusChip } from '@/components/status-chip';
import { getSubscriptions } from './subscriptions-api';
import type { Subscription, SubscriptionActivationSource, SubscriptionStatus } from './subscription.types';
import { subscriptionDate, subscriptionMoney, subscriptionTone } from './subscription-utils';

export default function SubscriptionsPage() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState<SubscriptionStatus | ''>(''); const [source, setSource] = useState<SubscriptionActivationSource | ''>(''); const [page, setPage] = useState(0); const [limit, setLimit] = useState(20);
  const query = useQuery({ queryKey: ['subscriptions', { search, status, source, page, limit }], queryFn: () => getSubscriptions({ page: page + 1, limit, search: search || undefined, status: status || undefined, activationSource: source || undefined }) });
  const rows = query.data?.data.data ?? []; const total = query.data?.data.meta.total ?? 0; const filtered = Boolean(search || status || source); const reset = () => { setSearch(''); setStatus(''); setSource(''); setPage(0); };
  return <PageLayout><PageHeader title="Company Subscriptions" description="Manage commercial agreements, contracted seats, and lifecycle." breadcrumbs={['Admin', 'SaaS Management', 'Subscriptions']} primaryActionLabel="Assign Subscription" primaryActionTo="/saas/subscriptions/new" />
    <EnterpriseFilterCard title="Subscription Filters" description="Search and filters are applied before server pagination." loading={query.isFetching} summary={total ? `${total} subscription${total === 1 ? '' : 's'}` : filtered ? 'No subscriptions match the filters.' : 'No subscriptions have been created.'} search={<Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'minmax(240px, 1fr) 160px 190px auto auto' }, gap: 1 }}><EnterpriseFilterSearch label="Search subscriptions" placeholder="Company or plan" value={search} onChange={(v) => { setSearch(v); setPage(0); }} loading={query.isFetching} /><SelectFilter label="Status" value={status} values={['PENDING', 'ACTIVE', 'SUSPENDED', 'SUPERSEDED', 'CANCELLED', 'EXPIRED']} onChange={(v) => { setStatus(v as SubscriptionStatus | ''); setPage(0); }} /><SelectFilter label="Activation source" value={source} values={['MANUAL', 'PAYMENT', 'TRIAL_CONVERSION', 'COMPLIMENTARY']} onChange={(v) => { setSource(v as SubscriptionActivationSource | ''); setPage(0); }} /><Button startIcon={<RotateCcw size={17} />} disabled={!filtered} onClick={reset}>Reset</Button><Button variant="outlined" startIcon={<RefreshCw size={17} />} onClick={() => void query.refetch()}>Refresh</Button></Box>} />
    {query.isError ? <Alert severity="error" action={<Button onClick={() => void query.refetch()}>Retry</Button>}>Subscriptions could not be loaded.</Alert> : query.isLoading ? <LoadingSkeleton rows={6} /> : rows.length === 0 ? <Card><EmptyState title={filtered ? 'No matching subscriptions' : 'No subscriptions yet'} description={filtered ? 'Adjust or clear the filters.' : 'Assign the first company subscription.'} /></Card> : <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', xl: 'repeat(2, minmax(0, 1fr))' }, gap: 2 }}>{rows.map((row) => <SubscriptionCard key={row.id} value={row} />)}</Box>}
    <TablePagination component="div" count={total} page={page} rowsPerPage={limit} onPageChange={(_, v) => setPage(v)} onRowsPerPageChange={(e) => { setLimit(Number(e.target.value)); setPage(0); }} rowsPerPageOptions={[10, 20, 50]} />
  </PageLayout>;
}
function SelectFilter({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <TextField select size="small" label={label} value={value} onChange={(e) => onChange(e.target.value)}><MenuItem value="">All</MenuItem>{values.map((v) => <MenuItem key={v} value={v}>{v.replaceAll('_', ' ')}</MenuItem>)}</TextField>; }
function SubscriptionCard({ value }: { value: Subscription }) { const price = value.billingModelSnapshot === 'PER_USER' ? value.pricePerSeatMinor : value.customRecurringPriceMinor; return <Card variant="outlined"><CardContent><Stack gap={1.5}><Stack direction="row" justifyContent="space-between" gap={1}><Box><Typography component={Link} to={`/saas/subscriptions/${value.id}`} variant="h6" color="text.primary" fontWeight={850} sx={{ textDecoration: 'none' }}>{value.company.name}</Typography><Typography variant="body2" color="text.secondary">{value.planNameSnapshot} · {value.planCodeSnapshot}</Typography></Box><StatusChip label={value.status} tone={subscriptionTone(value.status)} /></Stack><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 1 }}><Fact label="Seats" value={String(value.seatQuantity)} /><Fact label="Effective price" value={subscriptionMoney(price, value.currency)} /><Fact label="Billing interval" value={value.billingInterval} /><Fact label="Activation source" value={value.activationSource.replaceAll('_', ' ')} /><Fact label="Current period" value={value.currentPeriodStart ? `${subscriptionDate(value.currentPeriodStart)} – ${subscriptionDate(value.currentPeriodEnd)}` : 'Not set'} /></Box><Button component={Link} to={`/saas/subscriptions/${value.id}`} variant="outlined">View details</Button></Stack></CardContent></Card>; }
function Fact({ label, value }: { label: string; value: string }) { return <Box><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="body2" fontWeight={700}>{value}</Typography></Box>; }
