import { Alert, Box, Button, Chip, Stack, Typography } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ConfirmDialog } from '@/components/confirm-dialog';
import { LoadingSkeleton } from '@/components/loading-skeleton';
import { PageHeader } from '@/components/page-header';
import { PageLayout } from '@/components/page-layout';
import { SectionCard } from '@/components/section-card';
import { StatusChip } from '@/components/status-chip';
import { getSubscription, runSubscriptionAction } from './subscriptions-api';
import type { SubscriptionStatus } from './subscription.types';
import { subscriptionDate, subscriptionMoney, subscriptionTone } from './subscription-utils';

type Action = 'activate' | 'suspend' | 'resume' | 'cancel' | 'expire';
const actions: Record<SubscriptionStatus, Action[]> = { PENDING: ['activate', 'cancel'], ACTIVE: ['suspend', 'cancel', 'expire'], SUSPENDED: ['resume', 'cancel', 'expire'], SUPERSEDED: [], CANCELLED: [], EXPIRED: [] };
export default function SubscriptionDetailsPage() {
  const { id } = useParams(); const client = useQueryClient(); const [action, setAction] = useState<Action | null>(null); const [error, setError] = useState(''); const query = useQuery({ queryKey: ['subscription', id], queryFn: () => getSubscription(id!), enabled: Boolean(id) });
  const mutation = useMutation({ mutationFn: (next: Action) => runSubscriptionAction(id!, next), onSuccess: async () => { setAction(null); await client.invalidateQueries({ queryKey: ['subscription', id] }); await client.invalidateQueries({ queryKey: ['subscriptions'] }); }, onError: (e: unknown) => { const candidate = e as { response?: { data?: { message?: string } } }; setError(candidate.response?.data?.message ?? 'Subscription action failed.'); setAction(null); } });
  const value = query.data?.data; const price = value?.billingModelSnapshot === 'PER_USER' ? value.pricePerSeatMinor : value?.customRecurringPriceMinor ?? null; const availableActions = value ? actions[value.status].filter((next) => next !== 'expire' || Boolean(value.currentPeriodEnd && new Date(value.currentPeriodEnd) <= new Date())) : [];
  return <PageLayout><PageHeader title={value ? `${value.company.name} Subscription` : 'Subscription Details'} description="Effective commercial snapshot and lifecycle." breadcrumbs={['Admin', 'SaaS Management', 'Subscriptions', value?.company.name ?? 'Details']} />
    {error ? <Alert severity="error" onClose={() => setError('')}>{error}</Alert> : null}{query.isLoading ? <LoadingSkeleton rows={8} /> : query.isError ? <Alert severity="error" action={<Button onClick={() => void query.refetch()}>Retry</Button>}>Subscription could not be loaded.</Alert> : value ? <Stack gap={2}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={1}><StatusChip label={value.status} tone={subscriptionTone(value.status)} /><Stack direction="row" flexWrap="wrap" gap={1}>{value.status === 'ACTIVE' || value.status === 'SUSPENDED' ? <Button component={Link} to={`/saas/subscriptions/${value.id}/amend`} variant="outlined">Amend</Button> : null}{availableActions.map((next) => <Button key={next} variant={next === 'cancel' || next === 'expire' ? 'outlined' : 'contained'} color={next === 'cancel' || next === 'expire' ? 'error' : 'primary'} onClick={() => setAction(next)}>{next}</Button>)}</Stack></Stack>
      <SectionCard title="Agreement" description="Plan lineage and immutable effective terms."><Box sx={grid}><Fact label="Company" value={value.company.name} /><Fact label="Plan snapshot" value={value.planNameSnapshot} /><Fact label="Plan code snapshot" value={value.planCodeSnapshot} /><Fact label="Billing model" value={value.billingModelSnapshot} /><Fact label="Billing interval" value={value.billingInterval} /><Fact label="Activation source" value={value.activationSource} /><Fact label="Contracted seats" value={String(value.seatQuantity)} /><Fact label="Effective price" value={subscriptionMoney(price, value.currency)} /></Box></SectionCard>
      <SectionCard title="Entitlements & Limits" description="These snapshots do not change when the catalog plan changes."><Typography variant="caption" color="text.secondary">Entitlements</Typography><Stack direction="row" flexWrap="wrap" gap={1} my={1}>{value.entitlementsSnapshot.length ? value.entitlementsSnapshot.map((key) => <Chip key={key} label={key} />) : <Typography>None</Typography>}</Stack><Typography variant="caption" color="text.secondary">Limits</Typography><Box sx={grid}>{Object.entries(value.limitsSnapshot).length ? Object.entries(value.limitsSnapshot).map(([key, amount]) => <Fact key={key} label={key} value={String(amount)} />) : <Typography>No limits configured</Typography>}</Box></SectionCard>
      <SectionCard title="Dates & Lineage" description="Lifecycle dates and retained amendment references."><Box sx={grid}><Fact label="Starts" value={subscriptionDate(value.startsAt)} /><Fact label="Period start" value={subscriptionDate(value.currentPeriodStart)} /><Fact label="Period end" value={subscriptionDate(value.currentPeriodEnd)} /><Fact label="Suspended" value={subscriptionDate(value.suspendedAt)} /><Fact label="Cancelled" value={subscriptionDate(value.cancelledAt)} /><Fact label="Ended" value={subscriptionDate(value.endedAt)} /><Fact label="Created" value={subscriptionDate(value.createdAt)} /><Fact label="Updated" value={subscriptionDate(value.updatedAt)} /><Fact label="Supersedes" value={value.supersedes ? `${value.supersedes.planNameSnapshot} (${value.supersedes.status})` : 'None'} /><Fact label="Successor" value={value.successors[0] ? `${value.successors[0].planNameSnapshot} (${value.successors[0].status})` : 'None'} /></Box>{value.successors[0] ? <Button component={Link} to={`/saas/subscriptions/${value.successors[0].id}`} sx={{ mt: 2 }}>View successor</Button> : null}</SectionCard>
      <Button component={Link} to={`/organization/companies/${value.company.id}`} variant="outlined">View company</Button><ConfirmDialog open={Boolean(action)} title={`${action ?? ''} subscription?`} description={action === 'cancel' || action === 'expire' ? 'This is a terminal lifecycle action and cannot be reversed.' : `Confirm the ${action ?? ''} lifecycle transition.`} confirmLabel={action ?? 'Confirm'} loading={mutation.isPending} onClose={() => { if (!mutation.isPending) setAction(null); }} onConfirm={() => { if (action) mutation.mutate(action); }} />
    </Stack> : <Alert severity="warning">Subscription not found.</Alert>}
  </PageLayout>;
}
function Fact({ label, value }: { label: string; value: string }) { return <Box minWidth={0}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography fontWeight={800} sx={{ overflowWrap: 'anywhere' }}>{value}</Typography></Box>; }
const grid = { display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))', lg: 'repeat(3, minmax(0, 1fr))' }, gap: 2 };
