import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, FormControlLabel, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { PageHeader } from '@/components/page-header';
import { PageLayout } from '@/components/page-layout';
import { getCompanies } from '@/features/organization/services/companies-api';
import { getEntitlementCatalog, getPlans } from '@/features/plans/plans-api';
import type { BillingInterval, SubscriptionActivationSource, SubscriptionPayload } from './subscription.types';
import { createSubscription } from './subscriptions-api';
import { subscriptionMoney } from './subscription-utils';

export default function SubscriptionCreatePage() {
  const navigate = useNavigate(); const companies = useQuery({ queryKey: ['companies', 'subscription-options'], queryFn: () => getCompanies({ page: 1, limit: 100 }) }); const plans = useQuery({ queryKey: ['plans', 'subscription-options'], queryFn: () => getPlans({ page: 1, limit: 100, status: 'ACTIVE' }) }); const catalog = useQuery({ queryKey: ['entitlement-catalog'], queryFn: getEntitlementCatalog });
  const [companyId, setCompanyId] = useState(''); const [planId, setPlanId] = useState(''); const [interval, setInterval] = useState<BillingInterval>('MONTHLY'); const [source, setSource] = useState<SubscriptionActivationSource>('MANUAL'); const [seats, setSeats] = useState('1'); const [customPrice, setCustomPrice] = useState(''); const [entitlements, setEntitlements] = useState<string[]>([]); const [maxStorageBytes, setMaxStorageBytes] = useState(''); const [screenshotRetentionDays, setScreenshotRetentionDays] = useState(''); const [periodStart, setPeriodStart] = useState(''); const [periodEnd, setPeriodEnd] = useState(''); const [error, setError] = useState('');
  const selected = plans.data?.data.data.find((p) => p.id === planId); const custom = selected?.billingModel === 'CUSTOM'; const catalogItems = useMemo(() => catalog.data?.data ?? [], [catalog.data]);
  const mutation = useMutation({ mutationFn: (payload: SubscriptionPayload) => createSubscription(payload), onSuccess: ({ data }) => navigate(`/saas/subscriptions/${data.id}`, { replace: true }), onError: (e: unknown) => { const candidate = e as { response?: { data?: { message?: string | string[] } } }; const message = candidate.response?.data?.message; setError(Array.isArray(message) ? message.join(', ') : message ?? 'Subscription could not be created.'); } });
  const submit = () => { setError(''); const limitValues = [maxStorageBytes, screenshotRetentionDays].filter(Boolean); if (!companyId || !selected || !Number.isInteger(Number(seats)) || Number(seats) < 1 || Boolean(periodStart) !== Boolean(periodEnd) || limitValues.some((value) => !Number.isInteger(Number(value)) || Number(value) < 0)) { setError('Choose a company and plan, enter valid seats and limits, and provide both period dates or neither.'); return; } const limits: Record<string, number> = {}; if (maxStorageBytes) limits.maxStorageBytes = Number(maxStorageBytes); if (screenshotRetentionDays) limits.screenshotRetentionDays = Number(screenshotRetentionDays); const payload: SubscriptionPayload = { companyId, planId, billingInterval: interval, activationSource: source, seatQuantity: Number(seats), ...(custom ? { customRecurringPriceMinor: source === 'COMPLIMENTARY' ? 0 : Math.round(Number(customPrice) * 100), entitlements, limits } : {}), ...(periodStart ? { currentPeriodStart: new Date(periodStart).toISOString(), currentPeriodEnd: new Date(periodEnd).toISOString() } : {}) }; mutation.mutate(payload); };
  return <PageLayout><PageHeader title="Assign Subscription" description="Create a pending commercial agreement. Activation is always a separate action." breadcrumbs={['Admin', 'SaaS Management', 'Subscriptions', 'Assign']} />
    {error ? <Alert severity="error">{error}</Alert> : null}<Card><CardContent><Stack gap={3} component="form" onSubmit={(e) => { e.preventDefault(); submit(); }}><Box sx={grid}><TextField select required label="Company" value={companyId} onChange={(e) => setCompanyId(e.target.value)}>{(companies.data?.data.data ?? []).map((v) => <MenuItem key={v.id} value={v.id}>{v.name} ({v.slug})</MenuItem>)}</TextField><TextField select required label="Plan" value={planId} onChange={(e) => { const next = e.target.value; setPlanId(next); const plan = plans.data?.data.data.find((v) => v.id === next); setSeats(String(Math.max(1, plan?.minSeats ?? 1))); setEntitlements(plan?.entitlements ?? []); setMaxStorageBytes(plan?.limits.maxStorageBytes?.toString() ?? ''); setScreenshotRetentionDays(plan?.limits.screenshotRetentionDays?.toString() ?? ''); }}>{(plans.data?.data.data ?? []).map((v) => <MenuItem key={v.id} value={v.id}>{v.name} ({v.code})</MenuItem>)}</TextField><TextField select label="Billing interval" value={interval} onChange={(e) => setInterval(e.target.value as BillingInterval)}>{['MONTHLY', 'YEARLY', 'CUSTOM'].map((v) => <MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField select label="Activation source" value={source} onChange={(e) => setSource(e.target.value as SubscriptionActivationSource)}>{['MANUAL', 'PAYMENT', 'TRIAL_CONVERSION', 'COMPLIMENTARY'].map((v) => <MenuItem key={v} value={v}>{v.replaceAll('_', ' ')}</MenuItem>)}</TextField><TextField required type="number" label="Contracted seats" value={seats} inputProps={{ min: selected?.minSeats ?? 1, max: selected?.maxSeats ?? undefined }} onChange={(e) => setSeats(e.target.value)} helperText={selected ? `Plan bounds: ${selected.minSeats ?? 1}–${selected.maxSeats ?? 'unlimited'}` : 'Choose a plan to view seat bounds.'} />{custom ? <TextField required={source !== 'COMPLIMENTARY'} type="number" label="Negotiated recurring price" value={source === 'COMPLIMENTARY' ? '0' : customPrice} disabled={source === 'COMPLIMENTARY'} inputProps={{ min: 0, step: '0.01' }} onChange={(e) => setCustomPrice(e.target.value)} helperText={`Amount in ${selected?.currency ?? 'INR'} for the selected interval.`} /> : <TextField label="Effective per-seat price" value={selected ? subscriptionMoney(source === 'COMPLIMENTARY' ? 0 : selected.monthlyPricePerSeatMinor, selected.currency) : ''} disabled helperText="Snapshotted from the selected plan." />}<TextField type="datetime-local" label="Current period start (optional)" value={periodStart} InputLabelProps={{ shrink: true }} onChange={(e) => setPeriodStart(e.target.value)} /><TextField type="datetime-local" label="Current period end (optional)" value={periodEnd} InputLabelProps={{ shrink: true }} onChange={(e) => setPeriodEnd(e.target.value)} /></Box>
      <Box><Typography fontWeight={800}>Effective entitlements</Typography><Typography variant="body2" color="text.secondary">Normal plans use their current catalog assignment. CUSTOM plans may select only available capabilities.</Typography><Stack direction="row" flexWrap="wrap" gap={1} mt={1}>{custom ? catalogItems.map((item) => { const disabled = !item.assignable || item.availability !== 'AVAILABLE'; return <FormControlLabel key={item.key} disabled={disabled} control={<Checkbox checked={entitlements.includes(item.key)} onChange={(_, checked) => setEntitlements((current) => checked ? [...current, item.key] : current.filter((key) => key !== item.key))} />} label={<Stack direction="row" gap={0.5} alignItems="center"><span>{item.name}</span>{disabled ? <Chip size="small" label="Coming Soon" /> : null}</Stack>} />; }) : (selected?.entitlements ?? []).map((key) => <Chip key={key} label={catalog.data?.data.find((item) => item.key === key)?.name ?? key} />)}</Stack></Box>
      {custom ? <Box><Typography fontWeight={800}>Negotiated limits</Typography><Typography variant="body2" color="text.secondary">Only controlled commercial limits are accepted; blank means unspecified.</Typography><Box sx={{ ...grid, mt: 1 }}><TextField type="number" label="Maximum storage (bytes)" value={maxStorageBytes} onChange={(e) => setMaxStorageBytes(e.target.value)} inputProps={{ min: 0, step: 1 }} /><TextField type="number" label="Screenshot retention (days)" value={screenshotRetentionDays} onChange={(e) => setScreenshotRetentionDays(e.target.value)} inputProps={{ min: 0, step: 1 }} /></Box></Box> : null}
      <Alert severity="info">This creates a PENDING subscription. It does not activate access, process payment, or alter company status.</Alert><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="flex-end" gap={1}><Button onClick={() => navigate('/saas/subscriptions')}>Cancel</Button><Button type="submit" variant="contained" disabled={mutation.isPending || companies.isLoading || plans.isLoading}>{mutation.isPending ? 'Creating…' : 'Create pending subscription'}</Button></Stack></Stack></CardContent></Card>
  </PageLayout>;
}
const grid = { display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))' }, gap: 2 };
