import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, FormControlLabel, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { PageHeader } from '@/components/page-header';
import { PageLayout } from '@/components/page-layout';
import { getCompanies } from '@/features/organization/services/companies-api';
import { getEntitlementCatalog, getPlans } from '@/features/plans/plans-api';
import type { BillingInterval, SubscriptionActivationSource, SubscriptionPayload } from './subscription.types';
import { createSubscription } from './subscriptions-api';
import { recurringPreview, subscriptionMoney } from './subscription-utils';

const directSources: SubscriptionActivationSource[] = ['MANUAL', 'PAYMENT', 'COMPLIMENTARY'];
export default function SubscriptionCreatePage() {
  const navigate = useNavigate();
  const companies = useQuery({ queryKey: ['companies', 'subscription-options'], queryFn: () => getCompanies({ page: 1, limit: 100 }) });
  const plans = useQuery({ queryKey: ['plans', 'subscription-options'], queryFn: () => getPlans({ page: 1, limit: 100, status: 'ACTIVE' }) });
  const catalog = useQuery({ queryKey: ['entitlement-catalog'], queryFn: getEntitlementCatalog });
  const [companyId, setCompanyId] = useState(''); const [planId, setPlanId] = useState(''); const [interval, setInterval] = useState<BillingInterval>('MONTHLY'); const [source, setSource] = useState<SubscriptionActivationSource>('MANUAL'); const [seats, setSeats] = useState('1'); const [periodStart, setPeriodStart] = useState(''); const [periodEnd, setPeriodEnd] = useState(''); const [error, setError] = useState('');
  const [entitlements, setEntitlements] = useState<string[]>([]); const [maxStorageBytes, setMaxStorageBytes] = useState(''); const [screenshotRetentionDays, setScreenshotRetentionDays] = useState(''); const catalogItems = useMemo(() => catalog.data?.data ?? [], [catalog.data]);
  const selected = plans.data?.data.data.find((plan) => plan.id === planId); const fixed = selected?.billingModel === 'CUSTOM'; const selectedPrice = selected?.recurringPrices.find((price) => price.billingInterval === interval); const amount = source === 'COMPLIMENTARY' ? '0' : selectedPrice?.amountMinor ?? null;
  const mutation = useMutation({ mutationFn: (payload: SubscriptionPayload) => createSubscription(payload), onSuccess: ({ data }) => navigate(`/saas/subscriptions/${data.id}`, { replace: true }), onError: (cause: unknown) => { const message = (cause as { response?: { data?: { message?: string | string[] } } }).response?.data?.message; setError(Array.isArray(message) ? message.join(', ') : message ?? 'Subscription could not be created.'); } });
  const submit = () => { setError(''); const quantity = Number(seats); const limitsValid = [maxStorageBytes, screenshotRetentionDays].filter(Boolean).every((value) => Number.isInteger(Number(value)) && Number(value) >= 0); if (!companyId || !selected || interval === 'CUSTOM' || (source !== 'COMPLIMENTARY' && !selectedPrice) || !Number.isInteger(quantity) || quantity < (selected.minSeats ?? 1) || (selected.maxSeats !== null && quantity > selected.maxSeats) || Boolean(periodStart) !== Boolean(periodEnd) || !limitsValid) { setError('Choose a company, configured Monthly or Yearly price, valid contracted seats and limits, and provide both period dates or neither.'); return; } const limits: Record<string, number> = {}; if (maxStorageBytes) limits.maxStorageBytes = Number(maxStorageBytes); if (screenshotRetentionDays) limits.screenshotRetentionDays = Number(screenshotRetentionDays); mutation.mutate({ companyId, planId, billingInterval: interval, activationSource: source, seatQuantity: quantity, ...(fixed ? { entitlements, limits } : {}), ...(periodStart ? { currentPeriodStart: new Date(periodStart).toISOString(), currentPeriodEnd: new Date(periodEnd).toISOString() } : {}) }); };
  return <PageLayout><PageHeader title="Assign Subscription" description="Create a pending commercial agreement. Activation is always a separate action." breadcrumbs={['Admin', 'SaaS Management', 'Subscriptions', 'Assign']} />
    {companies.isError ? <Alert severity="error" action={<Button onClick={() => void companies.refetch()}>Retry</Button>}>Companies could not be loaded.</Alert> : null}{plans.isError ? <Alert severity="error" action={<Button onClick={() => void plans.refetch()}>Retry</Button>}>Active plans could not be loaded.</Alert> : null}
    {!companies.isLoading && !companies.isError && companies.data?.data.data.length === 0 ? <Alert severity="warning">No companies are available for assignment.</Alert> : null}{!plans.isLoading && !plans.isError && plans.data?.data.data.length === 0 ? <Alert severity="warning">No active plans are available for assignment.</Alert> : null}{error ? <Alert severity="error">{error}</Alert> : null}
    <Card><CardContent><Stack gap={3} component="form" onSubmit={(event) => { event.preventDefault(); submit(); }}><Box sx={grid}>
      <TextField select required label="Company" value={companyId} onChange={(event) => setCompanyId(event.target.value)}>{(companies.data?.data.data ?? []).map((company) => <MenuItem key={company.id} value={company.id}>{company.name} ({company.slug})</MenuItem>)}</TextField>
      <TextField select required label="Plan" value={planId} onChange={(event) => { const next = event.target.value; const plan = plans.data?.data.data.find((item) => item.id === next); setPlanId(next); setSeats(String(Math.max(1, plan?.minSeats ?? 1))); setEntitlements(plan?.entitlements ?? []); setMaxStorageBytes(plan?.limits.maxStorageBytes?.toString() ?? ''); setScreenshotRetentionDays(plan?.limits.screenshotRetentionDays?.toString() ?? ''); }}>{(plans.data?.data.data ?? []).map((plan) => <MenuItem key={plan.id} value={plan.id}>{plan.name} ({plan.code})</MenuItem>)}</TextField>
      <TextField select label="Billing interval" value={interval} onChange={(event) => setInterval(event.target.value as BillingInterval)}>{['MONTHLY', 'YEARLY'].map((value) => <MenuItem key={value} value={value}>{value === 'MONTHLY' ? 'Monthly' : 'Yearly'}</MenuItem>)}</TextField>
      <TextField select label="Activation source" value={source} onChange={(event) => setSource(event.target.value as SubscriptionActivationSource)}>{directSources.map((value) => <MenuItem key={value} value={value}>{value.charAt(0) + value.slice(1).toLowerCase()}</MenuItem>)}</TextField>
      <TextField required type="number" label="Contracted seats" value={seats} inputProps={{ min: selected?.minSeats ?? 1, max: selected?.maxSeats ?? undefined }} onChange={(event) => setSeats(event.target.value)} helperText={selected ? `Plan bounds: ${selected.minSeats ?? 1}–${selected.maxSeats ?? 'unlimited'}` : 'Choose a plan to view seat bounds.'} />
      <TextField label={fixed ? 'Authoritative fixed total' : 'Authoritative per-user price'} value={selected ? subscriptionMoney(amount, selected.currency) : ''} disabled helperText="Read from the selected Plan interval; the server resolves the authoritative snapshot." />
      <TextField label="Informational recurring total" value={selected ? recurringPreview(amount, seats, fixed ? 'FIXED_TOTAL' : 'PER_USER_UNIT', selected.currency) : ''} disabled helperText={fixed ? 'Fixed total; contracted seats do not multiply this amount.' : 'Plan unit price × contracted seats. The server resolves and snapshots the authoritative final amount.'} />
      <TextField type="datetime-local" label="Current period start (optional)" value={periodStart} InputLabelProps={{ shrink: true }} onChange={(event) => setPeriodStart(event.target.value)} /><TextField type="datetime-local" label="Current period end (optional)" value={periodEnd} InputLabelProps={{ shrink: true }} onChange={(event) => setPeriodEnd(event.target.value)} />
    </Box>{fixed ? <Box><Typography fontWeight={800}>Negotiated CUSTOM terms</Typography><Typography variant="body2" color="text.secondary">Select only currently available capabilities. Blank limits remain unspecified.</Typography>{catalog.isError ? <Alert severity="error" action={<Button onClick={() => void catalog.refetch()}>Retry</Button>}>Entitlement catalog could not be loaded.</Alert> : <Stack direction="row" flexWrap="wrap" gap={1}>{catalogItems.map((item) => { const disabled = !item.assignable || item.availability !== 'AVAILABLE'; return <FormControlLabel key={item.key} disabled={disabled} control={<Checkbox checked={entitlements.includes(item.key)} onChange={(_, checked) => setEntitlements((current) => checked ? [...current, item.key] : current.filter((key) => key !== item.key))} />} label={<Stack direction="row" gap={0.5}><span>{item.name}</span>{disabled ? <Chip size="small" label="Coming Soon" /> : null}</Stack>} />; })}</Stack>}<Box sx={{ ...grid, mt: 1 }}><TextField type="number" label="Maximum storage (bytes)" value={maxStorageBytes} onChange={(event) => setMaxStorageBytes(event.target.value)} inputProps={{ min: 0, step: 1 }} /><TextField type="number" label="Screenshot retention (days)" value={screenshotRetentionDays} onChange={(event) => setScreenshotRetentionDays(event.target.value)} inputProps={{ min: 0, step: 1 }} /></Box></Box> : null}<Alert severity="info">This creates a Pending subscription. PAYMENT remains pending until an authoritative payment-completion flow activates it; this screen does not process payment or activate access.</Alert><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="flex-end" gap={1}><Button onClick={() => navigate('/saas/subscriptions')}>Cancel</Button><Button type="submit" variant="contained" disabled={mutation.isPending || companies.isLoading || plans.isLoading || companies.isError || plans.isError || (fixed && catalog.isLoading)}>{mutation.isPending ? 'Creating…' : 'Create pending subscription'}</Button></Stack></Stack></CardContent></Card>
  </PageLayout>;
}
const grid = { display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))' }, gap: 2 };
