import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, useLocation } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { PlatformRenewalFilterDraft } from '../components/PlatformRenewalFilters';
const { list, prepare, filterProps, listProps } = vi.hoisted(() => ({ list: vi.fn(), prepare: vi.fn(), filterProps: { current: null as Record<string, unknown> | null }, listProps: { current: null as Record<string, unknown> | null } }));
vi.mock('../platform-renewals-api', async original => ({ ...(await original<typeof import('../platform-renewals-api')>()), listPlatformRenewals: list, preparePlatformRenewal: prepare }));
vi.mock('../components/PlatformRenewalFilters', () => ({ PlatformRenewalFilters: (props: Record<string, unknown>) => { filterProps.current = props; return <div><button onClick={() => (props.onApply as () => void)()}>Apply mock</button><button onClick={() => (props.onClear as () => void)()}>Reset mock</button><button onClick={() => (props.onRefresh as () => void)()}>Refresh mock</button></div>; } }));
vi.mock('../components/PlatformRenewalList', () => ({ PlatformRenewalList: (props: Record<string, unknown>) => { listProps.current = props; return props.loading ? <div>Loading list</div> : <div>List ready: {(props.rows as Array<{ id: string }>).map(row => row.id).join(', ')}</div>; } }));
import PlatformRenewalsPage from './PlatformRenewalsPage';
const empty = { data: { data: [], meta: { page: 1, limit: 20, total: 0, totalPages: 0 } } };
describe('PlatformRenewalsPage', () => {
  beforeEach(() => { list.mockReset().mockResolvedValue(empty); prepare.mockReset(); filterProps.current = null; listProps.current = null; });
  it('announces loading and normalizes defaults', async () => { let resolve!: (v: unknown) => void; list.mockImplementation(() => new Promise(done => { resolve = done; })); renderPage(); expect(screen.getByRole('status')).toHaveTextContent('Loading renewals'); await waitFor(() => expect(list).toHaveBeenCalledWith({ page: 1, limit: 20 })); resolve(empty); await waitFor(() => expect(screen.queryByRole('status')).not.toBeInTheDocument()); expect(screen.getByTestId('location')).toHaveTextContent('?page=1&limit=20'); });
  it('hydrates supported URL filters and normalizes malformed values', async () => { const id = '11111111-1111-4111-8111-111111111111'; renderPage(`/?page=x&limit=7&companyId=${id}&status=APPLIED&from=bad&keep=yes`); await waitFor(() => expect(list).toHaveBeenCalledWith({ page: 1, limit: 20, companyId: id, status: 'APPLIED' })); expect(screen.getByTestId('location')).toHaveTextContent('keep=yes'); });
  it('keeps drafts silent and applies supported filters at page one', async () => { renderPage('/?page=3&limit=20'); await waitFor(() => expect(list).toHaveBeenCalledTimes(1)); act(() => (filterProps.current?.onChange as (d: PlatformRenewalFilterDraft) => void)({ ...(filterProps.current?.draft as PlatformRenewalFilterDraft), paymentId: '11111111-1111-4111-8111-111111111111', status: 'PREPARED' })); expect(list).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByText('Apply mock')); await waitFor(() => expect(list).toHaveBeenLastCalledWith(expect.objectContaining({ page: 1, paymentId: expect.any(String), status: 'PREPARED' }))); });
  it('resets filters and maps server pagination', async () => { renderPage('/?page=2&limit=50&status=BLOCKED&keep=yes'); await waitFor(() => expect(listProps.current).not.toBeNull()); fireEvent.click(screen.getByText('Reset mock')); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 1, limit: 50 })); act(() => (listProps.current?.onPaginationChange as (p: number, l: number) => void)(3, 50)); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 3, limit: 50 })); });
  it('retains rows and warns on background failure', async () => { let reject!: (e: unknown) => void; list.mockResolvedValueOnce({ data: { data: [{ id: 'renewal-1' }], meta: { page: 1, limit: 20, total: 1, totalPages: 1 } } }).mockImplementationOnce(() => new Promise((_, fail) => { reject = fail; })); renderPage(); expect(await screen.findByText('List ready: renewal-1')).toBeInTheDocument(); fireEvent.click(screen.getByText('Refresh mock')); reject({ isAxiosError: true, response: { status: 500, data: { message: 'secret' } } }); expect(await screen.findByText(/Showing the most recent available data/)).toBeInTheDocument(); expect(screen.queryByText('secret')).not.toBeInTheDocument(); });
  it.each([[400, 'filters are invalid'], [403, 'Access restricted'], [500, 'could not be loaded']])('renders safe %s error and retry', async (status, text) => { list.mockRejectedValue({ isAxiosError: true, response: { status, data: { message: 'secret' } } }); renderPage(); expect(await screen.findByText(new RegExp(text, 'i'))).toBeInTheDocument(); fireEvent.click(screen.getByText('Retry')); await waitFor(() => expect(list.mock.calls.length).toBeGreaterThan(1)); });
  it('prepares from the register and routes to the returned Renewal', async () => { const subscriptionId = '123e4567-e89b-42d3-a456-426614174000'; prepare.mockResolvedValue({ data: { renewalId: 'renewal-1', paymentId: 'payment-1', subscriptionId, cycleStart: '2026-01-01T00:00:00.000Z', cycleEnd: '2026-02-01T00:00:00.000Z', created: false } }); renderPage(); fireEvent.click(screen.getByRole('button', { name: 'Prepare Renewal' })); const dialog = screen.getByRole('dialog'); fireEvent.change(within(dialog).getByLabelText(/Subscription ID/), { target: { value: subscriptionId } }); fireEvent.click(within(dialog).getByRole('button', { name: 'Prepare Renewal' })); await waitFor(() => expect(screen.getByTestId('location')).toHaveTextContent('/billing/renewals/renewal-1')); });
});
function renderPage(initial = '/') { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[initial]}><PlatformRenewalsPage /><Location /></MemoryRouter></QueryClientProvider>); }
function Location() { const location = useLocation(); return <span data-testid="location">{location.pathname}{location.search}</span>; }
