import { describe, expect, it } from 'vitest';
import { formatBasisPoints, formatGstMoney } from './platform-gst-format';
import { localToIso, parseGstPolicyUrl, parseGstUrl, serializeGstPolicyUrl, serializeGstUrl } from './platform-gst-url';
describe('platform GST financial and URL safety', () => {
  it('formats monetary decimal strings beyond Number safe range without coercion', () => { expect(formatGstMoney('9007199254740991','INR')).toBe('INR 90071992547409.91'); expect(formatGstMoney('-101','INR')).toBe('INR -1.01'); });
  it('renders integer basis points exactly', () => { expect(formatBasisPoints(1801)).toBe('18.01%'); expect(formatBasisPoints(0)).toBe('0.00%'); });
  it('normalizes malformed, partial, and reversed filters while preserving unrelated params', () => { const parsed=parseGstUrl(new URLSearchParams('page=x&from=2090-02-01T00%3A00%3A00.000Z&to=2090-01-01T00%3A00%3A00.000Z&keep=yes')); expect(parsed.query).toEqual({page:1,limit:20}); expect(parsed.normalized.get('keep')).toBe('yes'); expect(parsed.normalized.has('from')).toBe(false); });
  it('serializes only an applied complete half-open range', () => { const result=serializeGstUrl({page:2,limit:50,from:'2090-01-01T00:00:00.000Z',to:'2090-02-01T00:00:00.000Z'},new URLSearchParams('keep=yes')); expect(result.toString()).toContain('from='); expect(result.get('keep')).toBe('yes'); });
  it('strictly validates local calendar dates including leap years',()=>{expect(localToIso('2092-02-29T10:00')).toMatch(/Z$/);expect(localToIso('2090-02-30T10:00')).toBeNull();expect(localToIso('2091-02-29T10:00')).toBeNull();expect(localToIso('2090-04-31T10:00')).toBeNull();expect(localToIso('2090-13-01T10:00')).toBeNull();});
  it('round-trips policy filters with prefixed keys and normalizes invalid values',()=>{const parsed=parseGstPolicyUrl(new URLSearchParams('view=policies&policyPage=3&policyStatus=ACTIVE&policyCurrency=INR&policyEffectiveAt=2090-01-01T00%3A00%3A00.000Z&page=7'));expect(parsed.query).toEqual({page:3,limit:20,status:'ACTIVE',currency:'INR',effectiveAt:'2090-01-01T00:00:00.000Z'});const reset=serializeGstPolicyUrl({page:1,limit:20},parsed.normalized);expect(reset.get('view')).toBe('policies');expect(reset.get('page')).toBe('7');expect(reset.has('policyStatus')).toBe(false);const invalid=parseGstPolicyUrl(new URLSearchParams('policyStatus=INVALID&policyEffectiveAt=bad'));expect(invalid.query).toEqual({page:1,limit:20});expect(invalid.shouldNormalize).toBe(true);});
});
