import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, useLocation, useNavigate } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { PlatformInvoiceFilterDraft } from '../components/PlatformInvoiceFilters';

const { list, filterProps, listProps } = vi.hoisted(() => ({ list: vi.fn(), filterProps: { current: null as Record<string, unknown> | null }, listProps: { current: null as Record<string, unknown> | null } }));
vi.mock('../platform-invoices-api', async (original) => ({ ...(await original<typeof import('../platform-invoices-api')>()), listPlatformInvoices: list }));
vi.mock('../components/PlatformInvoiceFilters', () => ({ PlatformInvoiceFilters: (props: Record<string, unknown>) => { filterProps.current = props; return <div><button onClick={() => (props.onApply as () => void)()}>Apply mock</button><button onClick={() => (props.onClear as () => void)()}>Clear mock</button><button onClick={() => (props.onRefresh as () => void)()}>Refresh mock</button></div>; } }));
vi.mock('../components/PlatformInvoiceList', () => ({ PlatformInvoiceList: (props: Record<string, unknown>) => { listProps.current = props; return props.loading ? <div>Loading list</div> : <div>List ready: {(props.rows as Array<{ id: string }>).map((row) => row.id).join(', ')}</div>; } }));
import PlatformInvoicesPage from './PlatformInvoicesPage';

const empty = { data: { data: [], meta: { page: 1, limit: 20, total: 0, totalPages: 0 } } };
describe('PlatformInvoicesPage', () => {
  beforeEach(() => { list.mockReset().mockResolvedValue(empty); filterProps.current = null; listProps.current = null; });
  it('announces initial loading and normalizes defaults', async () => { let resolve!: (value: unknown) => void; list.mockImplementation(() => new Promise((done) => { resolve = done; })); renderPage(); expect(screen.getByText('Loading list')).toBeInTheDocument(); expect(screen.getByRole('status')).toHaveTextContent('Loading invoices'); await waitFor(() => expect(list).toHaveBeenCalledWith({ page: 1, limit: 20 })); resolve(empty); await waitFor(() => expect(screen.queryByRole('status')).not.toBeInTheDocument()); expect(screen.getByTestId('location')).toHaveTextContent('?page=1&limit=20'); });
  it('keeps drafts query-silent, then trims and applies at page one', async () => { renderPage('/?page=4&limit=20&keep=yes'); await waitFor(() => expect(list).toHaveBeenCalledTimes(1)); act(() => (filterProps.current?.onChange as (value: PlatformInvoiceFilterDraft) => void)({ ...(filterProps.current?.draft as PlatformInvoiceFilterDraft), invoiceNumber: '  INV-1  ' })); expect(list).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByText('Apply mock')); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 1, limit: 20, invoiceNumber: 'INV-1' })); expect(screen.getByTestId('location')).toHaveTextContent('keep=yes'); });
  it('normalizes invalid UUIDs and clears while preserving unrelated params', async () => { renderPage('/?page=3&limit=50&companyId=bad&invoiceNumber=INV-1&keep=yes'); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 3, limit: 50, invoiceNumber: 'INV-1' })); fireEvent.click(screen.getByText('Clear mock')); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 1, limit: 50 })); expect(screen.getByTestId('location')).toHaveTextContent('keep=yes'); });
  it('rehydrates drafts across browser navigation', async () => { renderPage('/?page=1&limit=20&invoiceNumber=ONE'); await waitFor(() => expect(list).toHaveBeenLastCalledWith(expect.objectContaining({ invoiceNumber: 'ONE' }))); fireEvent.click(screen.getByText('Next URL')); await waitFor(() => expect((filterProps.current?.draft as PlatformInvoiceFilterDraft).invoiceNumber).toBe('TWO')); fireEvent.click(screen.getByText('Back URL')); await waitFor(() => expect((filterProps.current?.draft as PlatformInvoiceFilterDraft).invoiceNumber).toBe('ONE')); });
  it('maps page changes and resets page for a new limit', async () => { renderPage(); await waitFor(() => expect(listProps.current).not.toBeNull()); act(() => (listProps.current?.onPaginationChange as (page: number, limit: number) => void)(3, 20)); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 3, limit: 20 })); act(() => (listProps.current?.onPaginationChange as (page: number, limit: number) => void)(3, 100)); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 1, limit: 100 })); });
  it('retains prior rows and shows non-blocking progress during a page fetch', async () => { let resolve!: (value: unknown) => void; const first = { data: { data: [{ id: 'invoice-one' }], meta: { page: 1, limit: 20, total: 2, totalPages: 2 } } }; list.mockResolvedValueOnce(first).mockImplementationOnce(() => new Promise((done) => { resolve = done; })); renderPage(); await waitFor(() => expect((listProps.current?.rows as unknown[])).toHaveLength(1)); act(() => (listProps.current?.onPaginationChange as (page: number, limit: number) => void)(2, 20)); expect(await screen.findByLabelText('Updating Invoice register')).toBeInTheDocument(); expect((listProps.current?.rows as unknown[])).toHaveLength(1); resolve(empty); await waitFor(() => expect(screen.queryByLabelText('Updating Invoice register')).not.toBeInTheDocument()); });
  it('keeps retained rows visible and offers a safe retry after a background refetch fails', async () => { let reject!: (reason: unknown) => void; const first = { data: { data: [{ id: 'invoice-one' }], meta: { page: 1, limit: 20, total: 1, totalPages: 1 } } }; list.mockResolvedValueOnce(first).mockImplementationOnce(() => new Promise((_, fail) => { reject = fail; })); renderPage(); expect(await screen.findByText('List ready: invoice-one')).toBeInTheDocument(); fireEvent.click(screen.getByText('Refresh mock')); expect(await screen.findByLabelText('Updating Invoice register')).toBeInTheDocument(); expect(screen.getByText('List ready: invoice-one')).toBeInTheDocument(); reject({ isAxiosError: true, response: { status: 500, data: { message: 'raw database secret' } } }); expect(await screen.findByText("We couldn't refresh the Invoice list. Showing the most recent available data.")).toBeInTheDocument(); expect(screen.getByText('List ready: invoice-one')).toBeInTheDocument(); expect(screen.queryByText('raw database secret')).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Retry' })).toBeInTheDocument(); });
  it.each([[400, 'filters are invalid'], [403, 'Access restricted'], [500, 'could not be loaded']])('renders safe %s errors and retries', async (status, text) => { list.mockRejectedValue({ isAxiosError: true, response: { status, data: { message: 'raw database secret' } } }); renderPage(); expect(await screen.findByText(new RegExp(text, 'i'))).toBeInTheDocument(); expect(screen.queryByText('raw database secret')).not.toBeInTheDocument(); fireEvent.click(screen.getByText('Retry')); await waitFor(() => expect(list.mock.calls.length).toBeGreaterThan(1)); });
});
function renderPage(initial = '/') { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[initial]}><PlatformInvoicesPage /><Location /><History /></MemoryRouter></QueryClientProvider>); }
function Location() { const location = useLocation(); return <span data-testid="location">{location.search}</span>; }
function History() { const navigate = useNavigate(); return <><button onClick={() => navigate('/?page=1&limit=20&invoiceNumber=TWO')}>Next URL</button><button onClick={() => navigate(-1)}>Back URL</button></>; }
