import { fireEvent, render, screen, within } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { describe, expect, it, vi } from 'vitest';
import type { PlatformDunningListItem } from '../platform-dunning.types';
import { dunningDesktopColumns, PlatformDunningList } from './PlatformDunningList';
const row: PlatformDunningListItem = { active: true, classification: 'OPEN', reason: 'PAYMENT_FAILED', dueAt: '2026-09-01T00:00:00.000Z', renewal: { id: '11111111-1111-4111-8111-111111111111', status: 'PREPARED', cycleStart: '2026-09-01T00:00:00.000Z', cycleEnd: '2026-10-01T00:00:00.000Z', billingInterval: 'MONTHLY', createdAt: '2026-08-20T00:00:00.000Z' }, company: { id: '22222222-2222-4222-8222-222222222222', name: 'Acme' }, subscription: { id: '33333333-3333-4333-8333-333333333333', status: 'ACTIVE', plan: { id: '44444444-4444-4444-8444-444444444444', code: 'PRO', name: 'Pro' } }, payment: { id: '55555555-5555-4555-8555-555555555555', purpose: 'SUBSCRIPTION_RENEWAL', status: 'FAILED', amountMinor: '9007199254740993', currency: 'INR', provider: 'RAZORPAY', mode: 'TEST', failedAt: null, failureCode: null, safeFailureMessage: null }, latestProviderOrder: { id: '66666666-6666-4666-8666-666666666666', status: 'CLOSED', providerStatus: 'failed', createdAt: '2026-08-20T00:00:00.000Z', updatedAt: '2026-08-20T00:00:00.000Z' } };
describe('PlatformDunningList', () => {
  it.each(['dunning-desktop-list', 'dunning-mobile-list'])('renders safe evidence and exact money in %s', testId => { renderList([row]); const view = within(screen.getByTestId(testId)); expect(view.getByText('Acme')).toBeInTheDocument(); expect(view.getByText('INR 90071992547409.93')).toBeInTheDocument(); expect(view.getByText('PAYMENT FAILED')).toBeInTheDocument(); expect(view.getByRole('link', { name: 'View Details' })).toHaveAttribute('href', `/billing/dunning/${row.renewal.id}`); expect(view.queryByRole('button', { name: /recover|retry|charge/i })).not.toBeInTheDocument(); });
  it('renders an unavailable provider order safely', () => { renderList([{ ...row, latestProviderOrder: null }]); expect(screen.getAllByText('Not available').length).toBeGreaterThan(0); });
  it('keeps long desktop company, plan, and provider status values keyboard-discoverable', () => { const company = 'A company name long enough to require compact table truncation'; const plan = 'Enterprise Workforce Operations Plan'; const providerStatus = 'provider_status_with_long_safe_operational_context'; renderList([{ ...row, company: { ...row.company, name: company }, subscription: { ...row.subscription, plan: { ...row.subscription.plan, name: plan } }, latestProviderOrder: { ...row.latestProviderOrder!, providerStatus } }]); const desktop = within(screen.getByTestId('dunning-desktop-list')); expect(desktop.getByLabelText(company)).toHaveAttribute('tabindex', '0'); expect(desktop.getByLabelText(`${plan} (${row.subscription.plan.code})`)).toHaveAttribute('tabindex', '0'); expect(desktop.getByLabelText(providerStatus)).toHaveAttribute('tabindex', '0'); });
  it('keeps every required desktop column within the compact local minimum-width budget', () => { expect(dunningDesktopColumns.map(column => column.headerName)).toEqual(['Company', 'Subscription / Plan', 'Due / Cycle', 'Payment', 'Dunning Reason', 'Latest Provider Order', 'Action']); expect(dunningDesktopColumns.reduce((total, column) => total + (column.minWidth ?? column.width ?? 0), 0)).toBeLessThanOrEqual(865); expect(dunningDesktopColumns.at(-1)).toMatchObject({ field: 'action', width: 100, minWidth: 100, maxWidth: 100 }); });
  it.each([['PENDING', 'PAYMENT_PENDING'], ['AUTHORIZED', 'PAYMENT_AUTHORIZED'], ['FAILED', 'PAYMENT_FAILED']] as const)('keeps %s Payment truth distinct from provider-order evidence', (status, reason) => { renderList([{ ...row, payment: { ...row.payment, status }, reason }]); const desktop = within(screen.getByTestId('dunning-desktop-list')); expect(desktop.getByText(status)).toBeInTheDocument(); expect(desktop.getByText(reason.replace('_', ' '))).toBeInTheDocument(); expect(desktop.getByText('CLOSED')).toBeInTheDocument(); });
  it('emits server pagination changes from the desktop register', () => { const onPaginationChange = vi.fn(); render(<MemoryRouter><PlatformDunningList rows={[row]} total={41} page={1} limit={20} loading={false} filtered={false} onPaginationChange={onPaginationChange} /></MemoryRouter>); fireEvent.click(within(screen.getByTestId('dunning-desktop-list')).getByLabelText('Go to next page')); expect(onPaginationChange).toHaveBeenCalledWith(2, 20); });
  it.each([[false, 'No open Dunning records.'], [true, 'No Dunning records match the applied filters.']] as const)('renders the correct empty state', (filtered, title) => { renderList([], filtered); expect(screen.getAllByText(title).length).toBeGreaterThan(0); });
});
function renderList(rows: PlatformDunningListItem[], filtered = false) { return render(<MemoryRouter><PlatformDunningList rows={rows} total={rows.length} page={1} limit={20} loading={false} filtered={filtered} onPaginationChange={vi.fn()} /></MemoryRouter>); }
