import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { ReactNode } from 'react';
import { MemoryRouter, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
const api=vi.hoisted(()=>({transactions:vi.fn(),policies:vi.fn(),transaction:vi.fn(),policy:vi.fn()}));
vi.mock('../platform-gst-api',async original=>({...(await original<typeof import('../platform-gst-api')>()),listGstTransactions:api.transactions,listGstPolicies:api.policies,getGstTransaction:api.transaction,getGstPolicy:api.policy}));
import PlatformGstDetailsPage from './PlatformGstDetailsPage';
import PlatformGstPage from './PlatformGstPage';
const evidence={id:'evidence-id',paymentId:'payment-id',companyId:'company-id',sourceSubscriptionId:'subscription-id',policyVersionId:'policy-id',treatment:'TAXABLE',calculationVersion:1,decisionAt:'2090-01-02T00:00:00.000Z',currency:'INR',taxableSubtotalMinor:'9007199254740991',totalTaxMinor:'101',grossTotalMinor:'9007199254741092',jurisdictionClassification:'INTER_STATE',serviceClassification:'9983',roundingMode:'HALF_UP_MINOR_UNIT_PER_COMPONENT',sellerGstin:'27ABCDE1234F1Z5',sellerLegalName:'Seller Legal',sellerRegisteredState:'Maharashtra',sellerRegisteredStateCode:'27',buyerRegistrationStatus:'UNREGISTERED',buyerGstin:null,buyerBillingState:'Karnataka',buyerBillingStateCode:'29',placeOfSupplyState:'Karnataka',placeOfSupplyStateCode:'29',createdAt:'2090-01-02T00:00:00.000Z',company:{id:'company-id',name:'Example Company'},policyVersion:{policyCode:'SUBSCRIPTION_GST',version:2},components:[{type:'IGST',rateBasisPoints:1,taxableAmountMinor:'9007199254740991',taxAmountMinor:'101',currency:'INR'}],invoiceEvidence:{invoiceId:'invoice-id',policyCode:'SUBSCRIPTION_GST',policyVersion:2,taxableSubtotalMinor:'9007199254740991',totalTaxMinor:'101',grossTotalMinor:'9007199254741092',createdAt:'2090-01-03T00:00:00.000Z'}};
const policy={id:'policy-id',policyCode:'SUBSCRIPTION_GST',version:2,status:'ACTIVE',currency:'INR',treatment:'TAXABLE',effectiveFrom:'2090-01-01T00:00:00.000Z',effectiveUntil:null,totalRateBasisPoints:1800,cgstRateBasisPoints:900,sgstRateBasisPoints:900,igstRateBasisPoints:1800,serviceClassification:'9983',roundingMode:'HALF_UP_MINOR_UNIT_PER_COMPONENT',calculationVersion:1,createdByUserId:'actor-id',createdAt:'2089-12-01T00:00:00.000Z',updatedAt:'2089-12-01T00:00:00.000Z'};
describe('Platform GST pages',()=>{
 beforeEach(()=>{api.transactions.mockReset().mockResolvedValue({data:{data:[evidence],meta:{page:1,limit:20,total:1,totalPages:1}}});api.policies.mockReset().mockResolvedValue({data:{data:[policy],meta:{page:1,limit:20,total:1,totalPages:1}}});api.transaction.mockReset().mockResolvedValue({data:evidence});api.policy.mockReset().mockResolvedValue({data:policy});});
 it('renders persisted transaction totals and linkage without recalculating',async()=>{renderPage('/billing/gst-invoices');expect(await screen.findByText('Example Company')).toBeInTheDocument();expect(screen.getByText('INR 90071992547409.91')).toBeInTheDocument();expect(screen.getByText('invoice-id')).toBeInTheDocument();expect(screen.getByText('SUBSCRIPTION_GST v2')).toBeInTheDocument();});
 it('renders append-only policy history and no edit/delete action',async()=>{renderPage('/billing/gst-invoices?view=policies');expect(await screen.findByText('SUBSCRIPTION_GST v2')).toBeInTheDocument();expect(screen.getByText('18.00%')).toBeInTheDocument();expect(screen.queryByRole('button',{name:/edit|delete/i})).not.toBeInTheDocument();});
 it('hydrates policy filters from prefixed URL state and keeps controls accessible',async()=>{renderPage('/billing/gst-invoices?view=policies&policyPage=2&policyStatus=ACTIVE&policyCurrency=INR&policyEffectiveAt=2090-01-01T00%3A00%3A00.000Z');await waitFor(()=>expect(api.policies).toHaveBeenCalledWith({page:2,limit:20,status:'ACTIVE',currency:'INR',effectiveAt:'2090-01-01T00:00:00.000Z'}));expect(screen.getByLabelText('Status')).toHaveTextContent('ACTIVE');expect(screen.getByLabelText('Currency')).toHaveTextContent('INR');});
 it('applies, resets, and restores URL-backed policy filters through history',async()=>{renderPage('/billing/gst-invoices?view=policies&unrelated=kept');await screen.findByText('SUBSCRIPTION_GST v2');fireEvent.mouseDown(screen.getByLabelText('Status'));fireEvent.click(screen.getByRole('option',{name:'ACTIVE'}));fireEvent.click(screen.getByRole('button',{name:'Apply'}));await waitFor(()=>expect(screen.getByTestId('location')).toHaveTextContent('policyStatus=ACTIVE'));expect(screen.getByTestId('location')).toHaveTextContent('policyPage=1');expect(screen.getByTestId('location')).toHaveTextContent('unrelated=kept');fireEvent.click(screen.getByRole('button',{name:'Reset'}));await waitFor(()=>expect(screen.getByTestId('location')).not.toHaveTextContent('policyStatus'));fireEvent.click(screen.getByRole('button',{name:'Back'}));await waitFor(()=>expect(screen.getByLabelText('Status')).toHaveTextContent('ACTIVE'));expect(screen.getByTestId('location')).toHaveTextContent('policyStatus=ACTIVE');});
 it('shows retained transaction evidence with a warning after refresh failure and clears it after recovery',async()=>{renderPage('/billing/gst-invoices');expect(await screen.findByText('Example Company')).toBeInTheDocument();api.transactions.mockRejectedValueOnce(new Error('offline'));fireEvent.click(screen.getByRole('button',{name:'Refresh'}));expect(await screen.findByText(/latest GST transaction request failed/)).toBeInTheDocument();expect(screen.getByText('Example Company')).toBeInTheDocument();api.transactions.mockResolvedValueOnce({data:{data:[evidence],meta:{page:1,limit:20,total:1,totalPages:1}}});fireEvent.click(screen.getByRole('button',{name:'Retry'}));await waitFor(()=>expect(screen.queryByText(/latest GST transaction request failed/)).not.toBeInTheDocument());});
 it('shows policy initial failure and retained-data warning without blanking rows',async()=>{api.policies.mockRejectedValueOnce(new Error('initial'));const initial=renderPage('/billing/gst-invoices?view=policies');expect(await screen.findByText('GST policies could not be loaded.')).toBeInTheDocument();initial.unmount();api.policies.mockResolvedValueOnce({data:{data:[policy],meta:{page:1,limit:20,total:1,totalPages:1}}});renderPage('/billing/gst-invoices?view=policies');expect(await screen.findByText('SUBSCRIPTION_GST v2')).toBeInTheDocument();api.policies.mockRejectedValueOnce(new Error('offline'));fireEvent.mouseDown(screen.getByLabelText('Status'));fireEvent.click(screen.getByRole('option',{name:'ACTIVE'}));fireEvent.click(screen.getByRole('button',{name:'Apply'}));expect(await screen.findByText(/latest GST policy request failed/)).toBeInTheDocument();expect(screen.getByText('SUBSCRIPTION_GST v2')).toBeInTheDocument();});
 it('renders complete persisted transaction details and components',async()=>{renderDetails('/billing/gst-invoices/transactions/evidence-id','/billing/gst-invoices/transactions/:transactionId');expect(await screen.findByText('Seller Legal')).toBeInTheDocument();expect(screen.getByText('IGST')).toBeInTheDocument();expect(screen.getAllByText('INR 90071992547409.91').length).toBeGreaterThan(0);expect(screen.getAllByText('invoice-id').length).toBeGreaterThan(0);});
 it('renders policy details with rates and immutable semantics',async()=>{renderDetails('/billing/gst-invoices/policies/policy-id','/billing/gst-invoices/policies/:policyId');expect(await screen.findByText('SUBSCRIPTION_GST')).toBeInTheDocument();expect(screen.getAllByText('18.00%')).toHaveLength(2);expect(screen.getByText(/no edit or delete action/i)).toBeInTheDocument();});
});
function wrap(children:ReactNode,path:string){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter initialEntries={[path]}>{children}</MemoryRouter></QueryClientProvider>);}
function HistoryProbe(){const location=useLocation();const navigate=useNavigate();return <><span data-testid="location">{location.search}</span><button onClick={()=>navigate(-1)}>Back</button></>;}
function renderPage(path:string){return wrap(<><HistoryProbe/><Routes><Route path="/billing/gst-invoices" element={<PlatformGstPage/>}/></Routes></>,path);}
function renderDetails(path:string,route:string){return wrap(<Routes><Route path={route} element={<PlatformGstDetailsPage/>}/></Routes>,path);}
