export const ipcChannels = {
  tokensGet: 'tokens:get',
  tokensSet: 'tokens:set',
  tokensClear: 'tokens:clear',
  deviceGetInformation: 'device:get-information',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  appGetVersion: 'app:get-version',
  appSetAuthenticated: 'app:set-authenticated',
  appShowAndFocus: 'app:show-and-focus',
  systemGetIdleTimeSeconds: 'system:get-idle-time-seconds',
  systemGetForegroundWindow: 'system:get-foreground-window',
  systemIsScreenLocked: 'system:is-screen-locked',
  systemScreenLockChanged: 'system:screen-lock-changed',
  browserBridgeGetPairingInfo: 'browser-bridge:get-pairing-info',
  browserBridgeRegeneratePairingToken: 'browser-bridge:regenerate-pairing-token',
  browserBridgeGetLatestState: 'browser-bridge:get-latest-state',
  inputActivityStart: 'input-activity:start',
  inputActivityStop: 'input-activity:stop',
  inputActivitySnapshotAndReset: 'input-activity:snapshot-and-reset',
  screenshotCapture: 'screenshot:capture',
  screenshotListQueue: 'screenshot:list-queue',
  screenshotReadFile: 'screenshot:read-file',
  screenshotMarkUploaded: 'screenshot:mark-uploaded',
  screenshotMarkFailed: 'screenshot:mark-failed',
  appSignOutRequested: 'app:sign-out-requested',
} as const;
