import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { AxiosError } from 'axios';
import { beforeEach, describe, expect, it, vi } from 'vitest';
const { create } = vi.hoisted(() => ({ create: vi.fn() }));
vi.mock('../platform-gst-api', async original => ({ ...(await original<typeof import('../platform-gst-api')>()), createGstPolicy:create }));
import { CreateGstPolicyDialog, policyError } from './CreateGstPolicyDialog';
describe('CreateGstPolicyDialog', () => {
  beforeEach(()=>create.mockReset());
  it('starts with zero rates and makes no 18 percent assumption', () => { renderDialog(); expect(screen.getAllByDisplayValue('0')).toHaveLength(4); expect(screen.queryByDisplayValue('1800')).not.toBeInTheDocument(); expect(screen.getByText(/does not enable GST/)).toBeInTheDocument(); });
  it('validates reconciliation and effective interval before requesting', () => { renderDialog(); fireEvent.change(screen.getByLabelText(/Policy Code/),{target:{value:'GST_POLICY'}}); fireEvent.mouseDown(screen.getAllByRole('combobox')[1]); fireEvent.click(screen.getByRole('option',{name:'Taxable'})); fireEvent.click(screen.getByRole('button',{name:'Create Version'})); expect(screen.getByText(/require a service classification/)).toBeInTheDocument(); expect(create).not.toHaveBeenCalled(); });
  it('associates visible Select labels and rejects impossible or reversed intervals',()=>{renderDialog();expect(screen.getByLabelText('Status')).toBeInTheDocument();expect(screen.getByLabelText('Tax Treatment')).toBeInTheDocument();fireEvent.change(screen.getByLabelText(/Policy Code/),{target:{value:'GST_ZERO'}});fireEvent.change(screen.getByLabelText(/Effective From/),{target:{value:'2090-02-30T10:00'}});fireEvent.click(screen.getByRole('button',{name:'Create Version'}));expect(screen.getByText(/valid effective interval/)).toBeInTheDocument();fireEvent.change(screen.getByLabelText(/Effective From/),{target:{value:'2090-03-02T10:00'}});fireEvent.change(screen.getByLabelText(/Effective Until/),{target:{value:'2090-03-01T10:00'}});fireEvent.click(screen.getByRole('button',{name:'Create Version'}));expect(screen.getByText(/valid effective interval/)).toBeInTheDocument();expect(create).not.toHaveBeenCalled();});
  it('submits exact integer basis points once and prevents duplicate submission', async () => { create.mockResolvedValue({data:{}}); const {onClose}=renderDialog(); fireEvent.change(screen.getByLabelText(/Policy Code/),{target:{value:'GST_ZERO'}}); fireEvent.change(screen.getByLabelText(/Effective From/),{target:{value:'2090-01-01T00:00'}}); const form=screen.getByRole('button',{name:'Create Version'}).closest('form')!; fireEvent.submit(form); fireEvent.submit(form); await waitFor(()=>expect(create).toHaveBeenCalledTimes(1)); expect(create.mock.calls[0][0]).toMatchObject({policyCode:'GST_ZERO',status:'DRAFT',currency:'INR',totalRateBasisPoints:0}); await waitFor(()=>expect(onClose).toHaveBeenCalled()); });
  it('maps conflicts without exposing raw server details', () => { const error=new AxiosError('request failed'); error.response={status:409,data:{message:'secret database detail'},statusText:'Conflict',headers:{},config:{} as never}; expect(policyError(error)).toBe('This policy version conflicts with existing policy authority.'); expect(policyError(error)).not.toContain('secret database detail'); });
});
function renderDialog(){const client=new QueryClient({defaultOptions:{mutations:{retry:false}}});const onClose=vi.fn();const view=render(<QueryClientProvider client={client}><CreateGstPolicyDialog open onClose={onClose}/></QueryClientProvider>);return {...view,onClose};}
