import { fireEvent, render, screen } from '@testing-library/react';
import { useState } from 'react';
import { describe, expect, it, vi } from 'vitest';
import { PlatformInvoiceFilters, type PlatformInvoiceFilterDraft } from './PlatformInvoiceFilters';
const blank: PlatformInvoiceFilterDraft = { companyId: '', subscriptionId: '', sourcePaymentId: '', invoiceNumber: '', from: '', to: '' };
describe('PlatformInvoiceFilters', () => {
  it('exposes only locked exact filters and delegates actions', () => { const apply = vi.fn(); const refresh = vi.fn(); render(<PlatformInvoiceFilters draft={blank} filtered={false} fetching={false} summary="None" onChange={vi.fn()} onApply={apply} onClear={vi.fn()} onRefresh={refresh} />); for (const label of ['Company ID', 'Subscription ID', 'Source Payment ID', 'Invoice Number — exact match', 'Issued from — inclusive', 'Issued before — exclusive']) expect(screen.getByLabelText(label)).toBeInTheDocument(); expect(screen.queryByLabelText(/search|status|currency|plan/i)).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Apply' })); fireEvent.click(screen.getByRole('button', { name: 'Refresh' })); expect(apply).toHaveBeenCalledOnce(); expect(refresh).toHaveBeenCalledOnce(); expect(screen.getByRole('button', { name: 'Clear' })).toBeDisabled(); });
  it.each([['partial', '2026-09-01T10:00', ''], ['equal', '2026-09-01T10:00', '2026-09-01T10:00'], ['reversed', '2026-09-02T10:00', '2026-09-01T10:00'], ['malformed', '2026-02-30T10:00', '2026-03-01T10:00']])('blocks %s date ranges', (_, from, to) => { render(<PlatformInvoiceFilters draft={{ ...blank, from, to }} filtered={false} fetching={false} summary="None" onChange={vi.fn()} onApply={vi.fn()} onClear={vi.fn()} onRefresh={vi.fn()} />); expect(screen.getByRole('button', { name: 'Apply' })).toBeDisabled(); });
  it('keeps typing draft-only and Clear restores controls', () => { render(<Stateful />); fireEvent.change(screen.getByLabelText('Company ID'), { target: { value: 'draft' } }); expect(screen.getByLabelText('Company ID')).toHaveValue('draft'); fireEvent.click(screen.getByRole('button', { name: 'Clear' })); expect(screen.getByLabelText('Company ID')).toHaveValue(''); });
});
function Stateful() { const [draft, setDraft] = useState(blank); return <PlatformInvoiceFilters draft={draft} filtered={false} fetching={false} summary="None" onChange={setDraft} onApply={vi.fn()} onClear={() => setDraft(blank)} onRefresh={vi.fn()} />; }
