import { Alert, Box, Button, FormControl, IconButton, InputLabel, MenuItem, Select, Snackbar, Stack, Tooltip, Typography } from '@mui/material';
import { type GridColDef, type GridPaginationModel } from '@mui/x-data-grid';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, Download, Edit3, Eye, Power, RefreshCw, RotateCcw } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link as RouterLink, useLocation } from 'react-router-dom';
import { ConfirmDialog } from '@/components/confirm-dialog';
import { DataTable } from '@/components/data-table';
import { EmptyState } from '@/components/empty-state';
import { EnterpriseBarChart, EnterpriseChartCard, EnterpriseChartLegend } from '@/components/enterprise/charts';
import { EnterpriseFilterCard, EnterpriseFilterSearch, type EnterpriseActiveFilter } from '@/components/enterprise/filters';
import { LoadingSkeleton } from '@/components/loading-skeleton';
import { PageHeader } from '@/components/page-header';
import { PageLayout } from '@/components/page-layout/PageLayout';
import { SectionCard } from '@/components/section-card';
import { StatusChip } from '@/components/status-chip';
import { useBranches, useDepartments } from '@/features/organization/hooks';
import { deleteRotationPattern, exportRotationPatterns, getRotationPatterns, updateRotationPattern } from '../services/rotation-patterns-api';
import type { RotationPattern, RotationPatternScope } from '../types/rotation-pattern.types';
import { downloadBlob, emptyRotationPatternSummary, formatDateTime, localDateForFilename, responseBlob, rotationPatternScopeOptions, rotationScopeLabel, statusLabel, statusTone } from '../utils/rotation-pattern-utils';

const scopeColors = ['#2563EB', '#0891B2', '#7C3AED'];
export default function RotationPatternsPage() {
  const queryClient = useQueryClient();
  const location = useLocation();
  const [search, setSearch] = useState(''); const [scope, setScope] = useState<RotationPatternScope | ''>(''); const [branchId, setBranchId] = useState(''); const [departmentId, setDepartmentId] = useState(''); const [enabled, setEnabled] = useState<'true' | 'false' | ''>(''); const [pagination, setPagination] = useState<GridPaginationModel>({ page: 0, pageSize: 20 }); const [toggleTarget, setToggleTarget] = useState<RotationPattern | null>(null); const [archiveTarget, setArchiveTarget] = useState<RotationPattern | null>(null); const [toast, setToast] = useState<{ severity: 'success' | 'error'; message: string } | null>(location.state?.success ? { severity: 'success', message: location.state.success } : null);
  const branchesQuery = useBranches(); const departmentsQuery = useDepartments(); const branches = branchesQuery.data?.data.data ?? []; const departments = departmentsQuery.data?.data.data ?? [];
  const patternsQuery = useQuery({ queryKey: ['rotation-patterns', { page: pagination.page + 1, limit: pagination.pageSize, search, scope, branchId, departmentId, enabled }], queryFn: () => getRotationPatterns({ page: pagination.page + 1, limit: pagination.pageSize, search: search || undefined, scope: scope || undefined, branchId: branchId || undefined, departmentId: departmentId || undefined, enabled: enabled ? enabled === 'true' : undefined }) });
  const existenceQuery = useQuery({ queryKey: ['rotation-patterns', 'existence-check'], queryFn: () => getRotationPatterns({ page: 1, limit: 1 }), staleTime: 60_000 });
  const invalidate = async () => { await queryClient.invalidateQueries({ queryKey: ['rotation-patterns'] }); };
  const toggleMutation = useMutation({ mutationFn: (pattern: RotationPattern) => updateRotationPattern(pattern.id, { enabled: !pattern.enabled }), onSuccess: async (_, pattern) => { setToggleTarget(null); setToast({ severity: 'success', message: pattern.enabled ? 'Rotation pattern disabled.' : 'Rotation pattern enabled.' }); await invalidate(); }, onError: () => setToast({ severity: 'error', message: 'Pattern status could not be changed.' }) });
  const archiveMutation = useMutation({ mutationFn: (pattern: RotationPattern) => deleteRotationPattern(pattern.id), onSuccess: async () => { setArchiveTarget(null); setToast({ severity: 'success', message: 'Rotation pattern archived.' }); await invalidate(); }, onError: () => setToast({ severity: 'error', message: 'Pattern could not be archived.' }) });
  const exportMutation = useMutation({ mutationFn: () => exportRotationPatterns({ search: search || undefined, scope: scope || undefined, branchId: branchId || undefined, departmentId: departmentId || undefined, enabled: enabled ? enabled === 'true' : undefined }), onSuccess: (response) => { downloadBlob(responseBlob(response), `rotation-patterns-${localDateForFilename()}.csv`); setToast({ severity: 'success', message: 'Rotation patterns CSV export started.' }); }, onError: () => setToast({ severity: 'error', message: 'Rotation pattern export failed.' }) });
  const resetPage = () => setPagination((current) => ({ ...current, page: 0 })); const resetFilters = () => { setSearch(''); setScope(''); setBranchId(''); setDepartmentId(''); setEnabled(''); resetPage(); };
  const rows = patternsQuery.data?.data.data ?? []; const meta = patternsQuery.data?.data.meta; const summary = patternsQuery.data?.data.summary ?? emptyRotationPatternSummary(); const hasFilters = Boolean(search || scope || branchId || departmentId || enabled); const hasAnyPatterns = (existenceQuery.data?.data.meta.total ?? summary.total) > 0; const isEmpty = !patternsQuery.isFetching && !patternsQuery.isError && meta?.total === 0; const isFilteredEmpty = hasAnyPatterns && hasFilters; const filteredDepartments = departments.filter((department) => !branchId || department.branchId === branchId);
  const activeFilters = useMemo<EnterpriseActiveFilter[]>(() => { const filters: EnterpriseActiveFilter[] = []; if (search) filters.push({ key: 'search', label: 'Search', value: search, onRemove: () => { setSearch(''); resetPage(); } }); if (scope) filters.push({ key: 'scope', label: 'Scope', value: rotationPatternScopeOptions.find((option) => option.value === scope)?.label ?? scope, onRemove: () => { setScope(''); resetPage(); } }); if (branchId) filters.push({ key: 'branch', label: 'Branch', value: branches.find((branch) => branch.id === branchId)?.name ?? 'Selected branch', onRemove: () => { setBranchId(''); setDepartmentId(''); resetPage(); } }); if (departmentId) filters.push({ key: 'department', label: 'Department', value: departments.find((department) => department.id === departmentId)?.name ?? 'Selected department', onRemove: () => { setDepartmentId(''); resetPage(); } }); if (enabled) filters.push({ key: 'enabled', label: 'Status', value: enabled === 'true' ? 'Active' : 'Inactive', onRemove: () => { setEnabled(''); resetPage(); } }); return filters; }, [branchId, branches, departmentId, departments, enabled, scope, search]);
  const summaryText = useMemo(() => { if (!meta) return undefined; if (meta.total === 0) return hasFilters && hasAnyPatterns ? `No rotation patterns match the current filters. ${activeFilters.length} filters applied.` : undefined; const start = (meta.page - 1) * meta.limit + 1; const end = Math.min(meta.page * meta.limit, meta.total); return `Showing ${start}-${end} of ${meta.total} rotation patterns${hasFilters ? ` · ${activeFilters.length} filters applied` : ''}`; }, [activeFilters.length, hasAnyPatterns, hasFilters, meta]);
  const chartData = [{ label: 'Company', value: summary.companyScope, color: scopeColors[0] }, { label: 'Branch', value: summary.branchScope, color: scopeColors[1] }, { label: 'Department', value: summary.departmentScope, color: scopeColors[2] }]; const hasChartData = chartData.some((item) => item.value > 0);
  const columns = useMemo<GridColDef<RotationPattern>[]>(() => [
    { field: 'name', headerName: 'Pattern Name', minWidth: 240, flex: 1, renderCell: ({ row }) => <Box minWidth={0}><Typography fontWeight={850} noWrap>{row.name}</Typography><Typography variant="caption" color="text.secondary" noWrap>{row.code}</Typography></Box> },
    { field: 'scope', headerName: 'Scope', minWidth: 180, valueGetter: (_, row) => rotationScopeLabel(row) },
    { field: 'cycleLengthDays', headerName: 'Cycle', minWidth: 110, valueGetter: (_, row) => `${row.cycleLengthDays} days` },
    { field: 'anchorDate', headerName: 'Anchor', minWidth: 140, valueGetter: (_, row) => row.anchorDate?.slice(0, 10) ?? 'Not set' },
    { field: 'days', headerName: 'Pattern', minWidth: 170, valueGetter: (_, row) => `${row.days?.filter((day) => day.dayType === 'WORKING').length ?? 0} working days` },
    { field: 'enabled', headerName: 'Status', minWidth: 115, renderCell: ({ row }) => <StatusChip label={statusLabel(row.enabled)} tone={statusTone(row.enabled)} /> },
    { field: 'updatedAt', headerName: 'Updated At', minWidth: 170, valueGetter: (_, row) => formatDateTime(row.updatedAt) },
    { field: 'actions', headerName: 'Actions', sortable: false, filterable: false, minWidth: 190, renderCell: ({ row }) => <Stack direction="row" gap={0.25}><Tooltip title="Open"><IconButton component={RouterLink} to={`/scheduling/rotation-patterns/${row.id}`} size="small" aria-label={`Open ${row.name}`}><Eye size={17} /></IconButton></Tooltip><Tooltip title="Edit"><IconButton component={RouterLink} to={`/scheduling/rotation-patterns/${row.id}/edit`} size="small" aria-label={`Edit ${row.name}`}><Edit3 size={17} /></IconButton></Tooltip><Tooltip title={row.enabled ? 'Disable pattern' : 'Enable pattern'}><IconButton size="small" onClick={() => setToggleTarget(row)} aria-label={row.enabled ? `Disable ${row.name}` : `Enable ${row.name}`}><Power size={17} /></IconButton></Tooltip><Tooltip title="Archive pattern"><IconButton size="small" color="error" onClick={() => setArchiveTarget(row)} aria-label={`Archive ${row.name}`}><Archive size={17} /></IconButton></Tooltip></Stack> },
  ], []);
  return <PageLayout><PageHeader title="Rotation Patterns" description="Create reusable multi-day rotation cycles for draft shift rosters." breadcrumbs={['Admin', 'Scheduling', 'Rotation Patterns']} primaryActionLabel="Create Pattern" primaryActionTo="/scheduling/rotation-patterns/create" />
    <EnterpriseFilterCard title="Rotation Pattern Filters" description="Filter patterns by scope, branch, department, status, and search." loading={patternsQuery.isFetching || exportMutation.isPending} summary={summaryText} activeFilters={activeFilters} actions={<><Button variant="text" startIcon={<RotateCcw size={17} />} onClick={resetFilters} disabled={!hasFilters}>Reset</Button><Button variant="outlined" startIcon={<RefreshCw size={17} />} onClick={() => void patternsQuery.refetch()} disabled={patternsQuery.isFetching}>Refresh</Button><Tooltip title="Export filtered rotation patterns as CSV"><span><Button variant="outlined" startIcon={<Download size={17} />} disabled={exportMutation.isPending} onClick={() => exportMutation.mutate()}>{exportMutation.isPending ? 'Exporting...' : 'Export'}</Button></span></Tooltip></>} search={<EnterpriseFilterSearch value={search} label="Search patterns" placeholder="Search pattern name, code, or notes" loading={patternsQuery.isFetching} onChange={(value) => { setSearch(value); resetPage(); }} />} filters={<><FormControl size="small" fullWidth><InputLabel id="rotation-scope-filter-label">Scope</InputLabel><Select labelId="rotation-scope-filter-label" label="Scope" value={scope} onChange={(event) => { setScope(event.target.value as RotationPatternScope | ''); resetPage(); }}><MenuItem value="">All Scopes</MenuItem>{rotationPatternScopeOptions.map((option) => <MenuItem key={option.value} value={option.value}>{option.label}</MenuItem>)}</Select></FormControl><FormControl size="small" fullWidth><InputLabel id="rotation-status-filter-label">Status</InputLabel><Select labelId="rotation-status-filter-label" label="Status" value={enabled} onChange={(event) => { setEnabled(event.target.value as 'true' | 'false' | ''); resetPage(); }}><MenuItem value="">All Statuses</MenuItem><MenuItem value="true">Active</MenuItem><MenuItem value="false">Inactive</MenuItem></Select></FormControl><FormControl size="small" fullWidth><InputLabel id="rotation-branch-filter-label">Branch</InputLabel><Select labelId="rotation-branch-filter-label" label="Branch" value={branchId} onChange={(event) => { setBranchId(event.target.value); setDepartmentId(''); resetPage(); }} disabled={branchesQuery.isLoading}><MenuItem value="">All Branches</MenuItem>{branches.map((branch) => <MenuItem key={branch.id} value={branch.id}>{branch.name}</MenuItem>)}</Select></FormControl><FormControl size="small" fullWidth><InputLabel id="rotation-department-filter-label">Department</InputLabel><Select labelId="rotation-department-filter-label" label="Department" value={departmentId} onChange={(event) => { setDepartmentId(event.target.value); resetPage(); }} disabled={departmentsQuery.isLoading}><MenuItem value="">All Departments</MenuItem>{filteredDepartments.map((department) => <MenuItem key={department.id} value={department.id}>{department.name}</MenuItem>)}</Select></FormControl></>} />
    <EnterpriseChartCard title="Rotation Patterns by Scope" description={hasFilters ? 'Showing scope distribution for the current filtered rotation patterns.' : 'Showing scope distribution for all rotation patterns.'} loading={patternsQuery.isLoading} error={patternsQuery.isError} empty={false} retry={() => void patternsQuery.refetch()} height={hasChartData ? 190 : 110} accessibleSummary={`Rotation pattern summary. Total ${summary.total}. Active ${summary.active}. Inactive ${summary.inactive}.`}><Stack gap={1.25}><Stack direction="row" gap={1} flexWrap="wrap"><Kpi label="Total" value={summary.total} /><Kpi label="Active" value={summary.active} /><Kpi label="Inactive" value={summary.inactive} /><Kpi label="Company" value={summary.companyScope} /><Kpi label="Branch" value={summary.branchScope} /><Kpi label="Department" value={summary.departmentScope} /></Stack>{hasChartData ? <><EnterpriseBarChart data={chartData} categoryKey="label" valueKey="value" colors={scopeColors} height={150} valueFormatter={(value) => value.toLocaleString()} /><EnterpriseChartLegend items={chartData.map((item) => ({ label: item.label, color: item.color, value: item.value }))} /></> : null}</Stack></EnterpriseChartCard>
    {patternsQuery.isError ? <Alert severity="error">Rotation patterns could not be loaded.</Alert> : null}
    {isEmpty ? <SectionCard title="Rotation Patterns" description={isFilteredEmpty ? 'Adjust or clear filters to broaden the result set.' : 'Create your first reusable rotation cycle.'} action={isFilteredEmpty ? <Button variant="outlined" onClick={resetFilters}>Clear Filters</Button> : undefined}><EmptyState title={isFilteredEmpty ? 'No rotation patterns match the current filters' : 'No rotation patterns yet'} description={isFilteredEmpty ? 'Adjust or clear the active filters and try again.' : 'Create a reusable multi-day cycle before applying it to draft rosters.'} /></SectionCard> : <DataTable title="Rotation Patterns" rows={rows} columns={columns} showSearch={false} gridProps={{ loading: patternsQuery.isFetching, paginationMode: 'server', rowCount: meta?.total ?? 0, paginationModel: pagination, onPaginationModelChange: setPagination, getRowHeight: () => 64, slots: { loadingOverlay: () => <LoadingSkeleton rows={6} />, noRowsOverlay: () => <EmptyState title={isFilteredEmpty ? 'No rotation patterns match the current filters' : 'No rotation patterns yet'} description={isFilteredEmpty ? 'Adjust or clear the active filters and try again.' : 'Create a reusable multi-day cycle before applying it to draft rosters.'} /> } }} />}
    <ConfirmDialog open={Boolean(toggleTarget)} title={toggleTarget?.enabled ? 'Disable Rotation Pattern' : 'Enable Rotation Pattern'} description={toggleTarget?.enabled ? 'Disabled patterns cannot be applied to draft rosters.' : 'Enabled patterns can be applied to draft rosters.'} confirmLabel={toggleTarget?.enabled ? 'Disable Pattern' : 'Enable Pattern'} loading={toggleMutation.isPending} onClose={() => setToggleTarget(null)} onConfirm={() => toggleTarget && toggleMutation.mutate(toggleTarget)} />
    <ConfirmDialog open={Boolean(archiveTarget)} title="Archive Rotation Pattern" description="This removes the pattern from future roster planning. Existing roster days remain unchanged." confirmLabel="Archive Pattern" loading={archiveMutation.isPending} onClose={() => setArchiveTarget(null)} onConfirm={() => archiveTarget && archiveMutation.mutate(archiveTarget)} />
    <Snackbar open={Boolean(toast)} autoHideDuration={5000} onClose={() => setToast(null)}>{toast ? <Alert severity={toast.severity} onClose={() => setToast(null)}>{toast.message}</Alert> : undefined}</Snackbar>
  </PageLayout>;
}
function Kpi({ label, value }: { label: string; value: number }) { return <Box sx={{ minWidth: 108, px: 1.4, py: 0.9, borderRadius: 2, border: '1px solid', borderColor: 'divider', bgcolor: 'background.paper' }}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h5" fontWeight={900}>{value.toLocaleString()}</Typography></Box>; }