import { Alert, Box, Button, Card, CardContent, MenuItem, Stack, TablePagination, TextField, Typography } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { RefreshCw, RotateCcw } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { EmptyState } from '@/components/empty-state';
import { EnterpriseFilterCard, EnterpriseFilterSearch } from '@/components/enterprise/filters';
import { LoadingSkeleton } from '@/components/loading-skeleton';
import { PageHeader } from '@/components/page-header';
import { PageLayout } from '@/components/page-layout';
import { StatusChip } from '@/components/status-chip';
import { getPlans } from './plans-api';
import type { Plan, PlanStatus } from './plan.types';
import { moneyMinorString } from './plan-utils';

export default function PlansPage() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState<PlanStatus | ''>(''); const [visibility, setVisibility] = useState(''); const [page, setPage] = useState(0); const [limit, setLimit] = useState(20);
  const query = useQuery({ queryKey: ['plans', { search, status, visibility, page, limit }], queryFn: () => getPlans({ page: page + 1, limit, search: search || undefined, status: status || undefined, isPublic: visibility === '' ? undefined : visibility === 'public' }) });
  const rows = query.data?.data.data ?? []; const total = query.data?.data.meta.total ?? 0; const filtered = Boolean(search || status || visibility); const reset = () => { setSearch(''); setStatus(''); setVisibility(''); setPage(0); };
  return <PageLayout><PageHeader title="Plans & Pricing" description="Manage commercial catalog definitions, pricing, entitlements, and lifecycle." breadcrumbs={['Admin', 'SaaS Management', 'Plans & Pricing']} primaryActionLabel="Create Plan" primaryActionTo="/saas/plans/create" />
    <EnterpriseFilterCard title="Plan Filters" description="Filtering is applied before server pagination." loading={query.isFetching} summary={total ? `${total} plan${total === 1 ? '' : 's'}` : filtered ? 'No plans match the current filters.' : 'No plans have been created.'} search={<Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'minmax(260px, 1fr) 160px 160px auto auto' }, gap: 1 }}><EnterpriseFilterSearch label="Search plans" placeholder="Name or code" value={search} onChange={(value) => { setSearch(value); setPage(0); }} loading={query.isFetching} /><TextField select size="small" label="Status" value={status} onChange={(e) => { setStatus(e.target.value as PlanStatus | ''); setPage(0); }}><MenuItem value="">All statuses</MenuItem>{['DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED'].map((v) => <MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField select size="small" label="Visibility" value={visibility} onChange={(e) => { setVisibility(e.target.value); setPage(0); }}><MenuItem value="">All</MenuItem><MenuItem value="public">Public</MenuItem><MenuItem value="private">Private</MenuItem></TextField><Button startIcon={<RotateCcw size={17} />} onClick={reset} disabled={!filtered}>Reset</Button><Button variant="outlined" startIcon={<RefreshCw size={17} />} onClick={() => void query.refetch()}>Refresh</Button></Box>} />
    {query.isError ? <Alert severity="error" action={<Button onClick={() => void query.refetch()}>Retry</Button>}>Plans could not be loaded.</Alert> : query.isLoading ? <LoadingSkeleton rows={6} /> : rows.length === 0 ? <Card><EmptyState title={filtered ? 'No matching plans' : 'No plans yet'} description={filtered ? 'Adjust or clear the filters.' : 'Create the first commercial plan.'} /></Card> : <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: 'repeat(2, minmax(0, 1fr))' }, gap: 2 }}>{rows.map((plan) => <PlanCard key={plan.id} plan={plan} />)}</Box>}
    <TablePagination component="div" count={total} page={page} rowsPerPage={limit} onPageChange={(_, next) => setPage(next)} onRowsPerPageChange={(e) => { setLimit(Number(e.target.value)); setPage(0); }} rowsPerPageOptions={[10, 20, 50]} />
  </PageLayout>;
}
function PlanCard({ plan }: { plan: Plan }) { const seats = plan.minSeats === null && plan.maxSeats === null ? 'No catalog bounds' : `${plan.minSeats ?? 0}–${plan.maxSeats ?? 'Unlimited'} seats`; const basis = plan.billingModel === 'PER_USER' ? 'Per user' : 'Fixed total'; return <Card variant="outlined"><CardContent><Stack gap={1.5}><Stack direction="row" justifyContent="space-between" alignItems="flex-start" gap={1}><Box minWidth={0}><Typography component={Link} to={`/saas/plans/${plan.id}`} variant="h6" fontWeight={850} color="text.primary" sx={{ textDecoration: 'none' }}>{plan.name}</Typography><Typography variant="body2" color="text.secondary">{plan.code}</Typography></Box><StatusChip label={plan.status} tone={plan.status === 'ACTIVE' ? 'success' : plan.status === 'ARCHIVED' ? 'danger' : 'neutral'} /></Stack><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 1 }}><Price plan={plan} interval="MONTHLY" basis={basis} /><Price plan={plan} interval="YEARLY" basis={basis} /><Fact label="Billing" value={plan.billingModel === 'PER_USER' ? 'Per user' : 'Custom'} /><Fact label="Entitlements" value={String(plan.entitlements.length)} /><Fact label="Seat policy" value={seats} /><Fact label="Visibility" value={plan.isPublic ? 'Public' : 'Private'} /><Fact label="Recommended" value={plan.isRecommended ? 'Yes' : 'No'} /></Box><Stack direction="row" gap={1}><Button component={Link} to={`/saas/plans/${plan.id}`} variant="outlined">View</Button><Button component={Link} to={`/saas/plans/${plan.id}/edit`} disabled={plan.status === 'ARCHIVED'}>Edit</Button></Stack></Stack></CardContent></Card>; }
function Price({ plan, interval, basis }: { plan: Plan; interval: 'MONTHLY' | 'YEARLY'; basis: string }) { const price = plan.recurringPrices.find((item) => item.billingInterval === interval); return <Fact label={`${interval === 'MONTHLY' ? 'Monthly' : 'Yearly'} · ${basis}`} value={price ? moneyMinorString(price.amountMinor, price.currency) : 'Not configured'} />; }
function Fact({ label, value }: { label: string; value: string }) { return <Box minWidth={0}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="body2" fontWeight={700}>{value}</Typography></Box>; }
