import { Alert, Box, Button, Checkbox, Chip, CircularProgress, FormControlLabel, MenuItem, Stack, Switch, TextField, Typography } from '@mui/material';
import { useState } from 'react';
import { FormActions } from '@/components/form-actions';
import { SectionCard } from '@/components/section-card';
import type { EntitlementCatalogItem, Plan, PlanBillingModel, PlanPayload } from './plan.types';
import { normalizePlanCode, planCodeError } from './plan-utils';

export function PlanForm({ plan, catalog, catalogLoading, catalogError, retryCatalog, loading, error, onSubmit }: { plan?: Plan; catalog?: EntitlementCatalogItem[]; catalogLoading: boolean; catalogError: boolean; retryCatalog: () => void; loading: boolean; error?: string | null; onSubmit: (payload: PlanPayload) => Promise<void> }) {
  const [value, setValue] = useState(() => ({ code: plan?.code ?? '', name: plan?.name ?? '', description: plan?.description ?? '', billingModel: plan?.billingModel ?? 'PER_USER' as PlanBillingModel, price: plan?.monthlyPricePerSeatMinor === null || plan?.monthlyPricePerSeatMinor === undefined ? '' : (plan.monthlyPricePerSeatMinor / 100).toFixed(2), currency: plan?.currency ?? 'INR', minSeats: plan?.minSeats?.toString() ?? '', maxSeats: plan?.maxSeats?.toString() ?? '', sortOrder: plan?.sortOrder.toString() ?? '0', isPublic: plan?.isPublic ?? false, isRecommended: plan?.isRecommended ?? false, entitlements: plan?.entitlements ?? [], maxStorageBytes: plan?.limits.maxStorageBytes?.toString() ?? '', screenshotRetentionDays: plan?.limits.screenshotRetentionDays?.toString() ?? '' }));
  const [manualCode, setManualCode] = useState(Boolean(plan));
  const [codeTouched, setCodeTouched] = useState(false);
  const [submitAttempted, setSubmitAttempted] = useState(false);
  const set = <K extends keyof typeof value>(key: K, next: (typeof value)[K]) => setValue((old) => ({ ...old, [key]: next }));
  const catalogKeys = new Set(catalog?.map((item) => item.key) ?? []);
  const unresolved = value.entitlements.filter((key) => !catalogKeys.has(key));
  const groups = [...new Set(catalog?.map((item) => item.group) ?? [])];
  const codeValidation = planCodeError(value.code);
  const showCodeError = !plan && Boolean(codeValidation) && (codeTouched || submitAttempted);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSubmitAttempted(true); if (!catalog || catalogError || unresolved.length || codeValidation) return; const price = value.price.trim(); if (value.billingModel === 'PER_USER' && !/^\d+(\.\d{1,2})?$/.test(price)) return; const limits: Record<string, number> = {}; if (value.maxStorageBytes) limits.maxStorageBytes = Number(value.maxStorageBytes); if (value.screenshotRetentionDays) limits.screenshotRetentionDays = Number(value.screenshotRetentionDays); await onSubmit({ code: value.code, name: value.name.trim(), description: value.description.trim() || null, billingModel: value.billingModel, monthlyPricePerSeatMinor: price ? Math.round(Number(price) * 100) : null, currency: value.currency, minSeats: value.minSeats === '' ? null : Number(value.minSeats), maxSeats: value.maxSeats === '' ? null : Number(value.maxSeats), sortOrder: Number(value.sortOrder), isPublic: value.isPublic, isRecommended: value.isRecommended, entitlements: value.entitlements, limits }); };
  return <Stack component="form" gap={3} onSubmit={submit}>{error ? <Alert severity="error">{error}</Alert> : null}
    <SectionCard title="Plan Identity" description="The code is a permanent commercial identity and cannot be changed after creation."><Box sx={grid}><TextField required label="Plan name" value={value.name} onChange={(e) => { const name = e.target.value; setValue((old) => ({ ...old, name, ...(!plan && !manualCode ? { code: normalizePlanCode(name) } : {}) })); }} inputProps={{ maxLength: 120 }} /><TextField required label="Plan code" value={value.code} onChange={(e) => { if (plan) return; setManualCode(true); set('code', normalizePlanCode(e.target.value)); }} onBlur={() => setCodeTouched(true)} disabled={Boolean(plan)} error={showCodeError} helperText={plan ? 'Permanent commercial identity; this code cannot be changed.' : showCodeError ? codeValidation : manualCode ? 'Manually edited. Name changes will no longer overwrite this code.' : 'Auto-generated from Plan Name; editable before creation.'} inputProps={{ maxLength: 50 }} /><TextField label="Description" multiline minRows={3} value={value.description} onChange={(e) => set('description', e.target.value)} sx={{ gridColumn: '1 / -1' }} inputProps={{ maxLength: 1000 }} /></Box></SectionCard>
    <SectionCard title="Pricing" description="Base price before tax. Amounts are stored safely as integer minor units."><Box sx={grid}><TextField select label="Billing model" value={value.billingModel} onChange={(e) => set('billingModel', e.target.value as PlanBillingModel)}><MenuItem value="PER_USER">Per user</MenuItem><MenuItem value="CUSTOM">Custom</MenuItem></TextField><TextField required={value.billingModel === 'PER_USER'} disabled={value.billingModel === 'CUSTOM'} label="Monthly price per user" value={value.price} onChange={(e) => set('price', e.target.value)} inputProps={{ inputMode: 'decimal', pattern: '^\\d+(\\.\\d{1,2})?$' }} helperText="For example, 99.00 is stored as 9900; use at most two decimal places." /><TextField label="Currency" value={value.currency} disabled helperText="Launch currency: INR" /></Box></SectionCard>
    <SectionCard title="Seat Policy" description="Catalog eligibility rules only; purchased company seats belong to a future subscription."><Box sx={grid}><TextField type="number" label="Minimum seats" value={value.minSeats} onChange={(e) => set('minSeats', e.target.value)} inputProps={{ min: 0, step: 1 }} /><TextField type="number" label="Maximum seats" value={value.maxSeats} onChange={(e) => set('maxSeats', e.target.value)} inputProps={{ min: 0, step: 1 }} /></Box></SectionCard>
    <SectionCard title="Feature Entitlements" description="The canonical commercial catalog is loaded from the backend; only available capabilities can be assigned.">
      {catalogLoading ? <Stack direction="row" gap={1} alignItems="center"><CircularProgress size={20} /><Typography>Loading entitlement catalog…</Typography></Stack> : null}
      {catalogError ? <Alert severity="error" action={<Button color="inherit" onClick={retryCatalog}>Retry</Button>}>Entitlement catalog could not be loaded. Plan submission is disabled.</Alert> : null}
      {unresolved.length ? <Alert severity="warning" sx={{ mb: 2 }}>This plan contains unknown or deprecated entitlements: {unresolved.join(', ')}. They are preserved locally and must be resolved before saving.</Alert> : null}
      {groups.map((group) => <Box key={group} mb={2.5}><Typography fontWeight={800} mb={1}>{group}</Typography><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))' }, gap: 1 }}>{catalog?.filter((item) => item.group === group).sort((a, b) => a.sortOrder - b.sortOrder).map((item) => { const disabled = !item.assignable || item.availability !== 'AVAILABLE'; return <Box key={item.key} sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 2, p: 1.5, opacity: disabled ? 0.7 : 1 }}><FormControlLabel disabled={disabled} control={<Checkbox checked={value.entitlements.includes(item.key)} onChange={(e) => set('entitlements', e.target.checked ? [...value.entitlements, item.key] : value.entitlements.filter((key) => key !== item.key))} />} label={<Stack direction="row" gap={1} alignItems="center" flexWrap="wrap"><Typography fontWeight={700}>{item.name}</Typography>{disabled ? <Chip size="small" label="Coming Soon" color="warning" variant="outlined" /> : null}</Stack>} /><Typography variant="body2" color="text.secondary" ml={4}>{item.description}</Typography></Box>; })}</Box></Box>)}
    </SectionCard>
    <SectionCard title="Commercial Limits" description="Only controlled catalog allowances are accepted; blank means unspecified."><Box sx={grid}><TextField type="number" label="Maximum storage (bytes)" value={value.maxStorageBytes} onChange={(e) => set('maxStorageBytes', e.target.value)} inputProps={{ min: 0, step: 1 }} /><TextField type="number" label="Screenshot retention (days)" value={value.screenshotRetentionDays} onChange={(e) => set('screenshotRetentionDays', e.target.value)} inputProps={{ min: 0, step: 1 }} /></Box></SectionCard>
    <SectionCard title="Visibility" description="Control catalog presentation and ordering."><Box sx={grid}><TextField type="number" label="Sort order" value={value.sortOrder} onChange={(e) => set('sortOrder', e.target.value)} inputProps={{ min: 0, step: 1 }} /><Stack><FormControlLabel control={<Switch checked={value.isPublic} onChange={(e) => set('isPublic', e.target.checked)} />} label="Public" /><FormControlLabel control={<Switch checked={value.isRecommended} onChange={(e) => set('isRecommended', e.target.checked)} />} label="Recommended" /></Stack></Box></SectionCard>
    <FormActions cancelTo={plan ? `/saas/plans/${plan.id}` : '/saas/plans'} submitLabel={plan ? 'Save changes' : 'Create plan'} loading={loading || catalogLoading} disabled={!catalog || catalogError || unresolved.length > 0} />
  </Stack>;
}
const grid = { display: 'grid', gridTemplateColumns: { xs: 'minmax(0, 1fr)', md: 'repeat(2, minmax(0, 1fr))', lg: 'repeat(3, minmax(0, 1fr))' }, gap: 2 };
