import { render, screen } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { PlatformRole } from '../platform-access.types';
const captured = vi.hoisted(() => ({ props: null as Record<string, unknown> | null }));
const responsive = vi.hoisted(() => ({ width: 390, query: '' }));
vi.mock('@/components/data-table', () => ({ DataTable: (props: Record<string, unknown>) => { captured.props = props; return <div data-testid="desktop-grid">Desktop grid</div>; } }));
vi.mock('@mui/material/useMediaQuery', () => ({ default: (query: string) => { responsive.query = query; const minimum = Number(query.match(/min-width:\s*(\d+)px/)?.[1] ?? Number.POSITIVE_INFINITY); return responsive.width >= minimum; } }));
import { PlatformRoleList } from './PlatformRoleList';

const role: PlatformRole = { id: 'role-1', companyId: null, key: 'long_global_role_key', name: 'Long Global Role Name', description: 'A detailed authoritative description that remains discoverable.', systemName: 'SUPER_ADMIN', createdAt: '', updatedAt: '', permissions: [{ assignedAt: '', permission: { id: 'permission-1', key: 'people:view', description: 'View people' } }], _count: { users: 7 } };
describe('PlatformRoleList', () => {
  beforeEach(() => { captured.props = null; responsive.width = 390; responsive.query = ''; });
  it('selects only the DataGrid register at a wide desktop width matching lg', () => { responsive.width = 1440; renderList([role]); expect(responsive.query).toMatch(/min-width:\s*1200px/); expect(screen.getByTestId('platform-roles-desktop')).toContainElement(screen.getByTestId('desktop-grid')); expect(screen.queryByTestId('platform-roles-cards')).not.toBeInTheDocument(); expect(captured.props?.rows).toEqual([role]); });
  it.each([{ viewport: 'tablet', width: 900 }, { viewport: 'mobile', width: 390 }])('selects only complete role cards at a $viewport width below lg', ({ width }) => { responsive.width = width; renderList([role]); expect(responsive.query).toMatch(/min-width:\s*1200px/); const cards = screen.getByTestId('platform-roles-cards'); expect(screen.queryByTestId('platform-roles-desktop')).not.toBeInTheDocument(); expect(screen.queryByTestId('desktop-grid')).not.toBeInTheDocument(); for (const value of ['Long Global Role Name', 'long_global_role_key', 'SUPER_ADMIN', 'A detailed authoritative description', 'Assigned permissions', '1', 'Assigned users', '7', 'View Details']) expect(cards).toHaveTextContent(value); expect(screen.getByRole('button', { name: 'View Long Global Role Name details' })).toBeInTheDocument(); });
  it('disables misleading sorting and menus on columns without server sort authority', () => { responsive.width = 1440; renderList([role]); const columns = captured.props?.columns as Array<{ field: string; sortable?: boolean; disableColumnMenu?: boolean }>; for (const field of ['role', 'systemName', 'description', 'permissions', 'users', 'actions']) expect(columns.find((column) => column.field === field)).toMatchObject({ sortable: false, disableColumnMenu: true }); });
  it.each([[false, 'No platform roles available.'], [true, 'No roles match the applied filters.']])('renders the correct empty state when filtered=%s', (filtered, title) => { responsive.width = 1440; renderList([], filtered); const gridProps = captured.props?.gridProps as { slots: { noRowsOverlay: () => React.ReactNode }; paginationMode: string }; expect(gridProps.paginationMode).toBe('server'); render(<>{gridProps.slots.noRowsOverlay()}</>); expect(screen.getAllByText(title).length).toBeGreaterThan(0); });
  it('announces initial role loading without rendering either register branch', () => { render(<PlatformRoleList rows={[]} total={0} page={1} limit={20} loading filtered={false} onView={vi.fn()} onPaginationChange={vi.fn()} />); expect(screen.getByRole('status', { name: 'Loading platform roles' })).toBeInTheDocument(); expect(screen.queryByTestId('platform-roles-desktop')).not.toBeInTheDocument(); });
});
function renderList(rows: PlatformRole[], filtered = false) { return render(<PlatformRoleList rows={rows} total={rows.length} page={1} limit={20} loading={false} filtered={filtered} onView={vi.fn()} onPaginationChange={vi.fn()} />); }
