import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import axios from 'axios';
import { beforeEach, describe, expect, it, vi } from 'vitest';
const { getAudit } = vi.hoisted(() => ({ getAudit: vi.fn() }));
vi.mock('../platform-access-api', async (original) => ({ ...(await original<typeof import('../platform-access-api')>()), getPlatformAuditLog: getAudit }));
import { PlatformAuditDetailsDialog } from './PlatformAuditDetailsDialog';
const audit = { id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', companyId: null, actorUserId: '11111111-1111-4111-8111-111111111111', action: 'PLATFORM_USER_UPDATED', entityType: 'User', entityId: '22222222-2222-4222-8222-222222222222', ipAddress: '127.0.0.1', userAgent: 'Browser agent', createdAt: '2026-01-01T00:00:00Z', actor: { id: '11111111-1111-4111-8111-111111111111', email: 'admin@example.invalid', firstName: 'Platform', lastName: 'Admin', status: 'ACTIVE' } };
describe('PlatformAuditDetailsDialog', () => {
  beforeEach(() => getAudit.mockReset().mockResolvedValue({ data: audit }));
  it('announces loading without a dangling description reference, then presents described authoritative details', async () => { getAudit.mockImplementationOnce(() => new Promise(() => undefined)); const view = renderDialog(); const loadingDialog = screen.getByRole('dialog', { name: 'Audit Details' }); expect(screen.getByRole('status', { name: 'Loading audit details' })).toBeInTheDocument(); expect(loadingDialog).not.toHaveAttribute('aria-describedby'); view.unmount(); getAudit.mockResolvedValue({ data: audit }); renderDialog(); const dialog = await screen.findByRole('dialog', { name: 'Audit Details' }); await within(dialog).findByText(audit.id); expect(dialog).toHaveAttribute('aria-describedby', 'platform-audit-authority'); expect(document.getElementById('platform-audit-authority')).toBeInTheDocument(); for (const value of [audit.id, audit.action, 'Platform Admin', audit.actor.email, audit.actor.id, audit.actor.status, audit.entityType, audit.entityId, audit.ipAddress, audit.userAgent, 'Read-only platform audit evidence']) expect(dialog).toHaveTextContent(value); expect(getAudit).toHaveBeenCalledWith(audit.id); expect(dialog).not.toHaveTextContent('metadata'); expect(within(dialog).queryByRole('button', { name: /edit|delete|clear|export/i })).not.toBeInTheDocument(); });
  it('handles nullable actor/source/target fields safely', async () => { getAudit.mockResolvedValue({ data: { ...audit, actor: null, actorUserId: null, entityId: null, ipAddress: null, userAgent: null } }); renderDialog(); const dialog = await screen.findByRole('dialog', { name: 'Audit Details' }); await within(dialog).findByText('System / unavailable'); expect(dialog).toHaveTextContent('Unavailable'); });
  it('sanitizes a not-found error without a dangling description reference and functionally retries', async () => { const headers = new axios.AxiosHeaders(); const notFound = new axios.AxiosError('raw secret', undefined, undefined, undefined, { status: 404, data: { message: 'raw secret' }, headers, config: { headers }, statusText: '' }); getAudit.mockRejectedValueOnce(notFound).mockResolvedValueOnce({ data: audit }); renderDialog(); expect(await screen.findByText(/no longer exists/i)).toBeInTheDocument(); expect(screen.getByRole('dialog', { name: 'Audit Details' })).not.toHaveAttribute('aria-describedby'); expect(screen.queryByText(/raw secret/i)).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Retry' })); await waitFor(() => expect(getAudit).toHaveBeenCalledTimes(2)); expect(await screen.findByText('PLATFORM_USER_UPDATED')).toBeInTheDocument(); });
});
function renderDialog() { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return render(<QueryClientProvider client={client}><PlatformAuditDetailsDialog open auditId={audit.id} onClose={vi.fn()} /></QueryClientProvider>); }
