import { render, screen } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { PlatformAuditRecord } from '../platform-access.types';
const captured = vi.hoisted(() => ({ props: null as Record<string, unknown> | null })); const responsive = vi.hoisted(() => ({ width: 390, query: '' }));
vi.mock('@/components/data-table', () => ({ DataTable: (props: Record<string, unknown>) => { captured.props = props; return <div data-testid="desktop-grid">Desktop audit grid</div>; } }));
vi.mock('@mui/material/useMediaQuery', () => ({ default: (query: string) => { responsive.query = query; const minimum = Number(query.match(/min-width:\s*(\d+)px/)?.[1] ?? Infinity); return responsive.width >= minimum; } }));
import { PlatformAuditList } from './PlatformAuditList';
const row: PlatformAuditRecord = { id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', companyId: null, actorUserId: '11111111-1111-4111-8111-111111111111', action: 'PLATFORM_USER_UPDATED_WITH_LONG_ACTION', entityType: 'User', entityId: '22222222-2222-4222-8222-222222222222', ipAddress: '127.0.0.1', userAgent: 'Sensitive dense user agent', createdAt: '2026-01-01T00:00:00Z', actor: { id: '11111111-1111-4111-8111-111111111111', email: 'admin@example.invalid', firstName: 'Platform', lastName: 'Admin', status: 'ACTIVE' } };
describe('PlatformAuditList', () => {
  beforeEach(() => { captured.props = null; responsive.width = 390; responsive.query = ''; });
  it('selects only the desktop DataGrid at 1440px without dense user-agent or metadata fields', () => { responsive.width = 1440; renderList([row]); expect(responsive.query).toMatch(/1200px/); expect(screen.getByTestId('desktop-grid')).toBeInTheDocument(); expect(screen.queryByTestId('platform-audits-cards')).not.toBeInTheDocument(); const columns = captured.props?.columns as Array<{ field: string }>; expect(columns.map(({ field }) => field)).toEqual(['createdAt', 'action', 'actor', 'target', 'ipAddress', 'actions']); expect(columns.map(({ field }) => field)).not.toContain('userAgent'); expect(columns.map(({ field }) => field)).not.toContain('metadata'); });
  it.each([{ viewport: 'tablet', width: 900 }, { viewport: 'mobile', width: 390 }])('selects complete cards only at $viewport width', ({ width }) => { responsive.width = width; renderList([row]); const cards = screen.getByTestId('platform-audits-cards'); expect(screen.queryByTestId('platform-audits-desktop')).not.toBeInTheDocument(); for (const value of [row.action, 'Platform Admin', row.actor!.email, row.entityType, row.entityId!, row.ipAddress!, 'View Details']) expect(cards).toHaveTextContent(value); expect(cards).not.toHaveTextContent(row.userAgent!); });
  it('uses safe actor, target, and IP fallbacks', () => { renderList([{ ...row, actor: null, actorUserId: null, entityId: null, ipAddress: null }]); const cards = screen.getByTestId('platform-audits-cards'); expect(cards).toHaveTextContent('System / unavailable'); expect(cards).toHaveTextContent('No target ID'); expect(cards).toHaveTextContent('Unavailable'); });
  it.each([[false, 'No platform audit records available.'], [true, 'No audit records match the applied filters.']])('distinguishes empty state filtered=%s', (filtered, title) => { renderList([], filtered); expect(screen.getByText(title)).toBeInTheDocument(); });
  it('announces initial loading', () => { render(<PlatformAuditList rows={[]} total={0} page={1} limit={20} loading filtered={false} onView={vi.fn()} onPaginationChange={vi.fn()} />); expect(screen.getByRole('status', { name: 'Loading platform audit logs' })).toBeInTheDocument(); });
});
function renderList(rows: PlatformAuditRecord[], filtered = false) { return render(<PlatformAuditList rows={rows} total={rows.length} page={1} limit={20} loading={false} filtered={filtered} onView={vi.fn()} onPaginationChange={vi.fn()} />); }
