import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { beforeEach, describe, expect, it, vi } from 'vitest';
const api = vi.hoisted(() => ({ get: vi.fn(), update: vi.fn(), status: vi.fn(), assign: vi.fn(), remove: vi.fn(), deleteUser: vi.fn() }));
vi.mock('../platform-access-api', async (original) => ({ ...(await original<typeof import('../platform-access-api')>()), getPlatformUser: api.get, updatePlatformUser: api.update, updatePlatformUserStatus: api.status, assignPlatformUserRole: api.assign, removePlatformUserRole: api.remove, deletePlatformUser: api.deleteUser }));
import { PlatformUserDetailsDialog } from './PlatformUserDetailsDialog';

const user = { id: 'user-1', companyId: null, email: 'admin@example.invalid', firstName: 'Ada', lastName: 'Admin', status: 'ACTIVE' as const, lastLoginAt: null, createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-02T00:00:00Z', deletedAt: null, roles: [{ assignedAt: '', role: { id: 'role-1', companyId: null, key: 'super_admin', name: 'Super Admin', systemName: 'SUPER_ADMIN' as const, description: null } }] };
const roles = [user.roles[0].role, { ...user.roles[0].role, id: 'role-2', key: 'auditor', name: 'Auditor', systemName: null }].map((role) => ({ ...role, createdAt: '', updatedAt: '', permissions: [], _count: { users: 1 } }));
describe('PlatformUserDetailsDialog', () => {
  beforeEach(() => { for (const mock of Object.values(api)) mock.mockReset(); api.get.mockResolvedValue({ data: user }); api.update.mockResolvedValue({ data: user }); api.status.mockResolvedValue({ data: user }); api.assign.mockResolvedValue({ data: user }); api.remove.mockResolvedValue({ data: user }); api.deleteUser.mockResolvedValue({ data: user }); });
  it('loads authority data and sends only safe profile fields', async () => { renderDialog(); await screen.findByDisplayValue('admin@example.invalid'); const dialog = screen.getByRole('dialog', { name: 'Manage Platform User' }); fireEvent.change(within(dialog).getByLabelText('Email *'), { target: { value: ' next@example.invalid ' } }); fireEvent.change(within(dialog).getByLabelText('First name *'), { target: { value: ' Next ' } }); fireEvent.click(within(dialog).getByRole('button', { name: 'Save Profile' })); await waitFor(() => expect(api.update.mock.calls[0]?.[0]).toBe('user-1')); expect(api.update.mock.calls[0]?.[1]).toEqual({ email: 'next@example.invalid', firstName: 'Next', lastName: 'Admin' }); expect(screen.queryByText(/password reset/i)).not.toBeInTheDocument(); }, 10_000);
  it('clears stale profile feedback and reports the latest successful status operation', async () => { renderDialog(); await screen.findByDisplayValue('admin@example.invalid'); const dialog = screen.getByRole('dialog', { name: 'Manage Platform User' }); fireEvent.click(within(dialog).getByRole('button', { name: 'Save Profile' })); expect(await screen.findByText('Profile updated.')).toBeInTheDocument(); fireEvent.click(within(dialog).getByRole('button', { name: 'SUSPENDED' })); expect(screen.queryByText('Profile updated.')).not.toBeInTheDocument(); const confirm = screen.getByRole('dialog', { name: 'Change platform user status?' }); fireEvent.click(within(confirm).getByRole('button', { name: 'Confirm' })); await waitFor(() => expect(api.status.mock.calls[0]?.slice(0, 2)).toEqual(['user-1', { status: 'SUSPENDED' }])); expect(await screen.findByText('Status updated.')).toBeInTheDocument(); });
  it('assigns only unassigned global roles and confirms removal', async () => { renderDialog(); await screen.findByDisplayValue('admin@example.invalid'); const dialog = screen.getByRole('dialog', { name: 'Manage Platform User' }); fireEvent.mouseDown(within(dialog).getByLabelText('Assign global role')); fireEvent.click(await screen.findByRole('option', { name: 'Auditor' })); fireEvent.click(within(dialog).getByRole('button', { name: 'Assign Role' })); await waitFor(() => expect(api.assign.mock.calls[0]?.slice(0, 2)).toEqual(['user-1', { roleId: 'role-2' }])); fireEvent.click(within(dialog).getByLabelText('Remove Super Admin')); const confirm = screen.getByRole('dialog', { name: 'Remove global role?' }); fireEvent.click(within(confirm).getByRole('button', { name: 'Confirm' })); await waitFor(() => expect(api.remove.mock.calls[0]?.slice(0, 2)).toEqual(['user-1', 'role-1'])); });
  it('requires explicit confirmation before soft delete', async () => { const onClose = vi.fn(); renderDialog(onClose); await screen.findByDisplayValue('admin@example.invalid'); const dialog = screen.getByRole('dialog', { name: 'Manage Platform User' }); fireEvent.click(within(dialog).getByRole('button', { name: 'Delete Platform User' })); expect(api.deleteUser).not.toHaveBeenCalled(); const confirm = screen.getByRole('dialog', { name: 'Soft delete platform user?' }); expect(confirm).toHaveTextContent('soft deletion'); fireEvent.click(within(confirm).getByRole('button', { name: 'Delete User' })); await waitFor(() => expect(api.deleteUser).toHaveBeenCalled()); expect(onClose).toHaveBeenCalled(); });
  it('keeps a protected status rejection inside the active confirmation and refetches authority', async () => { api.status.mockRejectedValue(protectedError()); renderDialog(); await screen.findByDisplayValue('admin@example.invalid'); fireEvent.click(screen.getByRole('button', { name: 'SUSPENDED' })); const confirm = screen.getByRole('dialog', { name: 'Change platform user status?' }); fireEvent.click(within(confirm).getByRole('button', { name: 'Confirm' })); expect(await within(confirm).findByRole('alert')).toHaveTextContent(/restricted/); expect(screen.queryByText('Status updated.')).not.toBeInTheDocument(); expect(api.get.mock.calls.length).toBeGreaterThan(1); expect(within(confirm).getByRole('button', { name: 'Cancel' })).toBeEnabled(); });
  it('keeps a rejected only-role removal coherent and preserves the assigned role', async () => { api.remove.mockRejectedValue(validationError()); renderDialog(); await screen.findByDisplayValue('admin@example.invalid'); fireEvent.click(screen.getByLabelText('Remove Super Admin')); const confirm = screen.getByRole('dialog', { name: 'Remove global role?' }); fireEvent.click(within(confirm).getByRole('button', { name: 'Confirm' })); expect(await within(confirm).findByRole('alert')).toHaveTextContent(/invalid/); expect(screen.getByText('Super Admin')).toBeInTheDocument(); expect(screen.queryByText('Role removed.')).not.toBeInTheDocument(); fireEvent.click(within(confirm).getByRole('button', { name: 'Cancel' })); expect(screen.queryByRole('dialog', { name: 'Remove global role?' })).not.toBeInTheDocument(); });
  it('keeps a protected delete rejection in context without closing the user', async () => { const onClose = vi.fn(); api.deleteUser.mockRejectedValue(protectedError()); renderDialog(onClose); await screen.findByDisplayValue('admin@example.invalid'); fireEvent.click(screen.getByRole('button', { name: 'Delete Platform User' })); const confirm = screen.getByRole('dialog', { name: 'Soft delete platform user?' }); fireEvent.click(within(confirm).getByRole('button', { name: 'Delete User' })); expect(await within(confirm).findByRole('alert')).toHaveTextContent(/restricted/); expect(onClose).not.toHaveBeenCalled(); expect(screen.getByDisplayValue('admin@example.invalid')).toBeInTheDocument(); });
});
function renderDialog(onClose = vi.fn()) { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><PlatformUserDetailsDialog open userId="user-1" roles={roles} onClose={onClose} /></QueryClientProvider>); }
function protectedError() { return { isAxiosError: true, response: { status: 403, data: { message: 'internal authority detail' } } }; }
function validationError() { return { isAxiosError: true, response: { status: 400, data: { message: 'internal validation detail' } } }; }
