import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, useLocation, useNavigate } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { PlatformAuditFilterDraft } from '../components/PlatformAuditFilters';
const mocks = vi.hoisted(() => ({ list: vi.fn(), detail: vi.fn(), filters: { current: null as Record<string, unknown> | null }, register: { current: null as Record<string, unknown> | null } }));
vi.mock('../platform-access-api', async (original) => ({ ...(await original<typeof import('../platform-access-api')>()), listPlatformAuditLogs: mocks.list, getPlatformAuditLog: mocks.detail }));
vi.mock('../components/PlatformAuditFilters', () => ({ PlatformAuditFilters: (props: Record<string, unknown>) => { mocks.filters.current = props; return <div><button onClick={() => (props.onApply as () => void)()}>Apply mock</button><button onClick={() => (props.onReset as () => void)()}>Reset mock</button><button onClick={() => (props.onRefresh as () => void)()}>Refresh mock</button></div>; } }));
vi.mock('../components/PlatformAuditList', async (original) => ({ ...(await original<typeof import('../components/PlatformAuditList')>()), PlatformAuditList: (props: Record<string, unknown>) => { mocks.register.current = props; const rows = props.rows as Array<{ id: string }>; return props.loading ? <div>Loading audits</div> : <div>Audits: {rows.map((row) => row.id).join(', ')}{rows.map((row) => <button key={row.id} onClick={() => (props.onView as (id: string) => void)(row.id)}>View {row.id}</button>)}</div>; } }));
import PlatformAuditLogsPage from './PlatformAuditLogsPage';
const empty = { data: { data: [], meta: { page: 1, limit: 20, total: 0, totalPages: 0 } } }; const populated = { data: { data: [{ id: 'audit-1' }], meta: { page: 1, limit: 20, total: 1, totalPages: 1 } } };
describe('PlatformAuditLogsPage', () => {
  beforeEach(() => { mocks.list.mockReset().mockResolvedValue(empty); mocks.detail.mockReset(); mocks.filters.current = mocks.register.current = null; });
  it('hydrates supported URL filters, normalizes invalid state, and preserves unrelated params', async () => { renderPage('/?page=x&action=AUTH_LOGIN&entityType=User&actorUserId=11111111-1111-4111-8111-111111111111&keep=yes'); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ page: 1, limit: 20, action: 'AUTH_LOGIN', entityType: 'User', actorUserId: '11111111-1111-4111-8111-111111111111' })); expect(screen.getByTestId('location')).toHaveTextContent('keep=yes'); expect(mocks.filters.current?.draft).toEqual({ action: 'AUTH_LOGIN', entityType: 'User', actorUserId: '11111111-1111-4111-8111-111111111111' }); });
  it('keeps drafts silent, applies at page one, resets, refreshes, and paginates', async () => { mocks.list.mockImplementation(({ page }: { page: number }) => Promise.resolve({ data: { data: [], meta: { page, limit: 20, total: 100, totalPages: 5 } } })); renderPage('/?page=3'); await waitFor(() => expect(mocks.list).toHaveBeenCalledTimes(1)); act(() => (mocks.filters.current?.onChange as (draft: PlatformAuditFilterDraft) => void)({ action: 'AUTH_LOGIN', entityType: 'User', actorUserId: '' })); expect(mocks.list).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByText('Apply mock')); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ page: 1, limit: 20, action: 'AUTH_LOGIN', entityType: 'User' })); fireEvent.click(screen.getByText('Reset mock')); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ page: 1, limit: 20 })); const calls = mocks.list.mock.calls.length; fireEvent.click(screen.getByText('Refresh mock')); await waitFor(() => expect(mocks.list.mock.calls.length).toBeGreaterThan(calls)); act(() => (mocks.register.current?.onPaginationChange as (page: number) => void)(2)); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ page: 2, limit: 20 })); });
  it('rehydrates the prior applied request and controls on browser Back', async () => { renderPage('/?page=1&action=AUTH_LOGIN&entityType=User'); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ page: 1, limit: 20, action: 'AUTH_LOGIN', entityType: 'User' })); act(() => (mocks.filters.current?.onChange as (draft: PlatformAuditFilterDraft) => void)({ action: 'PLATFORM_USER_UPDATED', entityType: 'User', actorUserId: '' })); fireEvent.click(screen.getByText('Apply mock')); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ page: 1, limit: 20, action: 'PLATFORM_USER_UPDATED', entityType: 'User' })); fireEvent.click(screen.getByText('Go back')); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ page: 1, limit: 20, action: 'AUTH_LOGIN', entityType: 'User' })); expect(mocks.filters.current?.draft).toEqual({ action: 'AUTH_LOGIN', entityType: 'User', actorUserId: '' }); });
  it.each([{ requested: 5, totalPages: 0, expected: 1 }, { requested: 5, totalPages: 2, expected: 2 }, { requested: 2, totalPages: 3, expected: 2 }])('normalizes page $requested against $totalPages pages to $expected without looping', async ({ requested, totalPages, expected }) => { mocks.list.mockImplementation(({ page }: { page: number }) => Promise.resolve({ data: { data: [], meta: { page, limit: 20, total: totalPages * 20, totalPages } } })); renderPage(`/?page=${requested}&keep=yes`); await waitFor(() => expect(screen.getByTestId('location')).toHaveTextContent(`page=${expected}`)); expect(screen.getByTestId('location')).toHaveTextContent('keep=yes'); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ page: expected, limit: 20 })); expect(mocks.list.mock.calls.length).toBeLessThanOrEqual(requested === expected ? 1 : 2); });
  it('retains successful rows and exposes a sanitized warning and Retry after background failure', async () => { let reject!: (error: unknown) => void; mocks.list.mockResolvedValueOnce(populated).mockImplementationOnce(() => new Promise((_, fail) => { reject = fail; })).mockResolvedValue(populated); renderPage(); expect(await screen.findByText('Audits: audit-1')).toBeInTheDocument(); fireEvent.click(screen.getByText('Refresh mock')); expect(screen.getByText('Audits: audit-1')).toBeInTheDocument(); reject(new Error('raw secret')); expect(await screen.findByText(/Showing the most recent available data/)).toBeInTheDocument(); expect(screen.getByText('Audits: audit-1')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Retry' })); await waitFor(() => expect(mocks.list).toHaveBeenCalledTimes(3)); });
  it('functionally retries a sanitized initial failure', async () => { mocks.list.mockRejectedValueOnce(new Error('secret')).mockResolvedValue(populated); renderPage(); expect(await screen.findByText(/could not be loaded/i)).toBeInTheDocument(); expect(screen.queryByText('secret')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Retry' })); expect(await screen.findByText('Audits: audit-1')).toBeInTheDocument(); expect(mocks.list).toHaveBeenCalledTimes(2); });
  it('keeps successful list data intact while a detail failure remains local, retries, and closes coherently', async () => { mocks.list.mockResolvedValue(populated); mocks.detail.mockRejectedValueOnce(new Error('raw detail secret')).mockResolvedValueOnce({ data: { id: 'audit-1', companyId: null, actorUserId: null, action: 'AUTH_LOGIN', entityType: 'User', entityId: null, ipAddress: null, userAgent: null, createdAt: '2026-01-01T00:00:00Z', actor: null } }); renderPage(); expect(await screen.findByText('Audits: audit-1')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'View audit-1' })); expect(await screen.findByText(/record could not be loaded/i)).toBeInTheDocument(); expect(screen.queryByText('raw detail secret')).not.toBeInTheDocument(); expect(screen.getByText('Audits: audit-1')).toBeInTheDocument(); expect(mocks.list).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByRole('button', { name: 'Retry' })); expect(await screen.findByText('AUTH_LOGIN')).toBeInTheDocument(); expect(mocks.detail).toHaveBeenCalledTimes(2); expect(mocks.list).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByRole('button', { name: 'Close' })); await waitFor(() => expect(screen.queryByRole('dialog', { name: 'Audit Details' })).not.toBeInTheDocument()); expect(screen.getByText('Audits: audit-1')).toBeInTheDocument(); });
});
function renderPage(initial = '/') { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[initial]}><PlatformAuditLogsPage /><Controls /></MemoryRouter></QueryClientProvider>); }
function Controls() { const location = useLocation(); const navigate = useNavigate(); return <><span data-testid="location">{location.pathname}{location.search}</span><button onClick={() => navigate(-1)}>Go back</button></>; }
