import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, useLocation, useNavigate } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { PlatformRoleFilterDraft } from '../components/PlatformRoleFilters';
const mocks = vi.hoisted(() => ({ listRoles: vi.fn(), listPermissions: vi.fn(), filter: { current: null as Record<string, unknown> | null }, list: { current: null as Record<string, unknown> | null }, catalog: { current: null as Record<string, unknown> | null } }));
vi.mock('../platform-access-api', async (original) => ({ ...(await original<typeof import('../platform-access-api')>()), listPlatformRoles: mocks.listRoles, listPlatformPermissions: mocks.listPermissions }));
vi.mock('../components/PlatformRoleFilters', () => ({ PlatformRoleFilters: (props: Record<string, unknown>) => { mocks.filter.current = props; return <div><button onClick={() => (props.onApply as () => void)()}>Apply mock</button><button onClick={() => (props.onReset as () => void)()}>Reset mock</button><button onClick={() => (props.onRefresh as () => void)()}>Refresh mock</button></div>; } }));
vi.mock('../components/PlatformRoleList', () => ({ PlatformRoleList: (props: Record<string, unknown>) => { mocks.list.current = props; return props.loading ? <div>Loading roles</div> : <div>Roles: {(props.rows as Array<{ id: string }>).map((row) => row.id).join(', ')}</div>; } }));
vi.mock('../components/PlatformPermissionCatalog', () => ({ PlatformPermissionCatalog: (props: Record<string, unknown>) => { mocks.catalog.current = props; return <div>Catalog: {(props.permissions as Array<{ key: string }>).map((item) => item.key).join(', ')}</div>; } }));
vi.mock('../components/PlatformRoleDetailsDialog', () => ({ PlatformRoleDetailsDialog: () => null }));
import PlatformRolesPermissionsPage from './PlatformRolesPermissionsPage';

const empty = { data: { data: [], meta: { page: 1, limit: 20, total: 0, totalPages: 0 } } };
describe('PlatformRolesPermissionsPage', () => {
  beforeEach(() => { mocks.listRoles.mockReset().mockResolvedValue(empty); mocks.listPermissions.mockReset().mockResolvedValue({ data: [] }); mocks.filter.current = mocks.list.current = mocks.catalog.current = null; });
  it('normalizes URL state, preserves unrelated params, and hydrates filters', async () => { renderPage('/?page=x&search=%20Admin%20&systemName=SUPER_ADMIN&keep=yes'); await waitFor(() => expect(mocks.listRoles).toHaveBeenCalledWith({ page: 1, limit: 20, search: 'Admin', systemName: 'SUPER_ADMIN' })); expect(screen.getByTestId('location')).toHaveTextContent('keep=yes'); expect(mocks.filter.current?.draft).toEqual({ search: 'Admin', systemName: 'SUPER_ADMIN' }); });
  it('keeps drafts silent then applies at page one, resets, refreshes, and paginates', async () => { mocks.listRoles.mockImplementation(({ page }: { page: number }) => Promise.resolve({ data: { data: [], meta: { page, limit: 20, total: 100, totalPages: 5 } } })); renderPage('/?page=3'); await waitFor(() => expect(mocks.listRoles).toHaveBeenCalledTimes(1)); act(() => (mocks.filter.current?.onChange as (draft: PlatformRoleFilterDraft) => void)({ search: 'admin', systemName: 'HR' })); expect(mocks.listRoles).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByText('Apply mock')); await waitFor(() => expect(mocks.listRoles).toHaveBeenLastCalledWith({ page: 1, limit: 20, search: 'admin', systemName: 'HR' })); fireEvent.click(screen.getByText('Reset mock')); await waitFor(() => expect(mocks.listRoles).toHaveBeenLastCalledWith({ page: 1, limit: 20 })); const calls = mocks.listRoles.mock.calls.length; fireEvent.click(screen.getByText('Refresh mock')); await waitFor(() => expect(mocks.listRoles.mock.calls.length).toBeGreaterThan(calls)); act(() => (mocks.list.current?.onPaginationChange as (page: number) => void)(2)); await waitFor(() => expect(mocks.listRoles).toHaveBeenLastCalledWith({ page: 2, limit: 20 })); });
  it('rehydrates the previous applied request and controls on browser Back', async () => { renderPage('/?page=1&search=Alpha&systemName=HR'); await waitFor(() => expect(mocks.listRoles).toHaveBeenLastCalledWith({ page: 1, limit: 20, search: 'Alpha', systemName: 'HR' })); act(() => (mocks.filter.current?.onChange as (draft: PlatformRoleFilterDraft) => void)({ search: 'Beta', systemName: 'MANAGER' })); fireEvent.click(screen.getByText('Apply mock')); await waitFor(() => expect(mocks.listRoles).toHaveBeenLastCalledWith({ page: 1, limit: 20, search: 'Beta', systemName: 'MANAGER' })); fireEvent.click(screen.getByText('Go back')); await waitFor(() => expect(mocks.listRoles).toHaveBeenLastCalledWith({ page: 1, limit: 20, search: 'Alpha', systemName: 'HR' })); expect(mocks.filter.current?.draft).toEqual({ search: 'Alpha', systemName: 'HR' }); });
  it.each([{ requested: 5, totalPages: 0, expected: 1 }, { requested: 5, totalPages: 2, expected: 2 }, { requested: 2, totalPages: 3, expected: 2 }])('normalizes requested page $requested against $totalPages pages to $expected', async ({ requested, totalPages, expected }) => { mocks.listRoles.mockImplementation(({ page }: { page: number }) => Promise.resolve({ data: { data: [], meta: { page, limit: 20, total: totalPages * 20, totalPages } } })); renderPage(`/?page=${requested}&keep=yes`); await waitFor(() => expect(screen.getByTestId('location')).toHaveTextContent(`page=${expected}`)); expect(screen.getByTestId('location')).toHaveTextContent('keep=yes'); await waitFor(() => expect(mocks.listRoles).toHaveBeenLastCalledWith({ page: expected, limit: 20 })); expect(mocks.listRoles.mock.calls.length).toBeLessThanOrEqual(requested === expected ? 1 : 2); });
  it('keeps role and catalog failures independent and preserves retained role data', async () => { mocks.listPermissions.mockRejectedValue(new Error('catalog secret')); mocks.listRoles.mockResolvedValueOnce({ data: { data: [{ id: 'role-1' }], meta: { page: 1, limit: 20, total: 1, totalPages: 1 } } }); renderPage(); expect(await screen.findByText('Roles: role-1')).toBeInTheDocument(); await waitFor(() => expect(mocks.catalog.current?.error).toMatch(/could not be loaded/i)); expect(screen.getByText(/Read-only reference/)).toBeInTheDocument(); });
  it('retains role rows and exposes a sanitized warning and Retry after background failure', async () => { let reject!: (error: unknown) => void; const populated = { data: { data: [{ id: 'role-1' }], meta: { page: 1, limit: 20, total: 1, totalPages: 1 } } }; mocks.listRoles.mockResolvedValueOnce(populated).mockImplementationOnce(() => new Promise((_, fail) => { reject = fail; })).mockResolvedValue(populated); renderPage(); expect(await screen.findByText('Roles: role-1')).toBeInTheDocument(); fireEvent.click(screen.getByText('Refresh mock')); expect(screen.getByText('Roles: role-1')).toBeInTheDocument(); reject(new Error('raw role secret')); expect(await screen.findByText(/Showing the most recent available data/)).toBeInTheDocument(); expect(screen.getByText('Roles: role-1')).toBeInTheDocument(); expect(screen.queryByText('raw role secret')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Retry' })); await waitFor(() => expect(mocks.listRoles).toHaveBeenCalledTimes(3)); });
  it('retries a safe initial role error and renders the recovered register without removing the catalog', async () => { const populated = { data: { data: [{ id: 'role-2' }], meta: { page: 1, limit: 20, total: 1, totalPages: 1 } } }; mocks.listRoles.mockRejectedValueOnce(new Error('role secret')).mockResolvedValue(populated); mocks.listPermissions.mockResolvedValue({ data: [{ id: 'permission-1', key: 'people:view', description: null }] }); renderPage(); expect(await screen.findByText(/Platform roles could not be loaded/)).toBeInTheDocument(); expect(screen.getByText('Catalog: people:view')).toBeInTheDocument(); expect(screen.queryByText('role secret')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Retry' })); expect(await screen.findByText('Roles: role-2')).toBeInTheDocument(); expect(mocks.listRoles).toHaveBeenCalledTimes(2); });
});
function renderPage(initial = '/') { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[initial]}><PlatformRolesPermissionsPage /><Controls /></MemoryRouter></QueryClientProvider>); }
function Controls() { const location = useLocation(); const navigate = useNavigate(); return <><span data-testid="location">{location.pathname}{location.search}</span><button onClick={() => navigate(-1)}>Go back</button></>; }
