ALTER TYPE "NotificationType" ADD VALUE 'SUBSCRIPTION_ACTIVATED';
ALTER TYPE "NotificationType" ADD VALUE 'SUBSCRIPTION_EXPIRED';
ALTER TYPE "NotificationType" ADD VALUE 'RENEWAL_APPLIED';
ALTER TYPE "NotificationType" ADD VALUE 'RENEWAL_BLOCKED';
ALTER TYPE "NotificationType" ADD VALUE 'RENEWAL_PREPARED';
