import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { BadRequestException, ConflictException, ForbiddenException } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { BillingInterval, PlanBillingModel, PlanStatus, RoleName, SubscriptionActivationSource, SubscriptionStatus, UserStatus } from '@prisma/client';
import { RolesGuard } from '../../common/guards/roles.guard';
import { SubscriptionsController } from './subscriptions.controller';
import { SubscriptionsService } from './subscriptions.service';
import { SeatUsageService } from '../usage-seats/seat-usage.service';

const actor = { id: 'actor-1', companyId: null, email: 'admin@example.com', firstName: 'Super', lastName: 'Admin', status: UserStatus.ACTIVE, roles: [RoleName.SUPER_ADMIN] };
const company = { id: 'company-1', name: 'Acme', deletedAt: null };
const plan = { id: 'plan-1', code: 'GROWTH', name: 'Growth', description: null, status: PlanStatus.ACTIVE, billingModel: PlanBillingModel.PER_USER, monthlyPricePerSeatMinor: 9900, currency: 'INR', minSeats: 2, maxSeats: 50, sortOrder: 1, isPublic: true, isRecommended: false, entitlements: ['workforce.attendance'], limits: { screenshotRetentionDays: 30 }, createdAt: new Date(), updatedAt: new Date(), archivedAt: null };
const dto = { companyId: company.id, planId: plan.id, billingInterval: BillingInterval.MONTHLY, activationSource: SubscriptionActivationSource.MANUAL, seatQuantity: 5 };
const subscription = { id: 'subscription-1', companyId: company.id, planId: plan.id, status: SubscriptionStatus.PENDING, activationSource: SubscriptionActivationSource.MANUAL, billingInterval: BillingInterval.MONTHLY, planCodeSnapshot: plan.code, planNameSnapshot: plan.name, billingModelSnapshot: plan.billingModel, currency: 'INR', pricePerSeatMinor: 9900, customRecurringPriceMinor: null, seatQuantity: 5, entitlementsSnapshot: plan.entitlements, limitsSnapshot: plan.limits, startsAt: null, currentPeriodStart: null, currentPeriodEnd: null, suspendedAt: null, cancelledAt: null, endedAt: null, supersedesSubscriptionId: null, createdAt: new Date(), updatedAt: new Date() };
const seatPolicy = new SeatUsageService({} as never);
const serviceWith = (prisma: Record<string, unknown>, used = 0) => new SubscriptionsService(prisma as never, {
  lockCompany: async () => undefined,
  countUsedSeats: async () => used,
  assessProposedCapacity: seatPolicy.assessProposedCapacity.bind(seatPolicy),
} as never);

function createHarness(selectedPlan = plan) {
  let createdData: Record<string, unknown> = {}; const audits: string[] = [];
  const tx = { companySubscription: { create: async ({ data }: { data: Record<string, unknown> }) => { createdData = data; return { ...subscription, ...data, companyId: company.id, planId: selectedPlan.id }; } }, auditLog: { create: async ({ data }: { data: { action: string } }) => { audits.push(data.action); return {}; } } };
  const service = serviceWith({ company: { findFirst: async () => company }, plan: { findUnique: async () => selectedPlan }, $transaction: async (callback: (value: typeof tx) => unknown) => callback(tx) });
  return { service, data: () => createdData, audits };
}

function lifecycleHarness(current = subscription, live: unknown = null, activeTrial: unknown = null) {
  const audits: string[] = []; let updated: Record<string, unknown> = {};
  const tx = { $queryRaw: async () => [{ id: company.id }], companyTrial: { findFirst: async () => activeTrial }, companySubscription: { findUnique: async () => current, findFirst: async () => live, update: async ({ data }: { data: Record<string, unknown> }) => { updated = data; return { ...current, ...data }; } }, auditLog: { create: async ({ data }: { data: { action: string } }) => { audits.push(data.action); return {}; } } };
  const service = serviceWith({ companySubscription: { findUnique: async () => current }, $transaction: async (callback: (value: typeof tx) => unknown) => callback(tx) });
  return { service, data: () => updated, audits };
}

function amendmentHarness(current = { ...subscription, status: SubscriptionStatus.ACTIVE }, selectedPlan = plan, failCreate = false, activeTrial: unknown = null, used = 0) {
  const events: string[] = []; const audits: string[] = []; let successorData: Record<string, unknown> = {}; let sourceUpdate: Record<string, unknown> = {};
  const tx = { $queryRaw: async () => [{ id: company.id }], companyTrial: { findFirst: async () => activeTrial }, companySubscription: {
    findUnique: async () => current,
    findFirst: async () => null,
    update: async ({ data }: { data: Record<string, unknown> }) => { sourceUpdate = data; events.push(`update:${String(data.status)}`); return { ...current, ...data }; },
    create: async ({ data }: { data: Record<string, unknown> }) => { events.push('create'); if (failCreate) throw new Error('create failed'); successorData = data; return { ...current, ...data, id: 'successor-1', supersedes: null, successors: [] }; },
  }, auditLog: { create: async ({ data }: { data: { action: string } }) => { audits.push(data.action); events.push(`audit:${data.action}`); return {}; } } };
  const service = serviceWith({ companySubscription: { findUnique: async () => current }, plan: { findUnique: async () => selectedPlan }, $transaction: async (callback: (value: typeof tx) => unknown) => callback(tx) }, used);
  return { service, events, audits, data: () => successorData, sourceUpdate: () => sourceUpdate };
}

describe('SubscriptionsService', () => {
  it('is SUPER_ADMIN-only and denies tenant roles', () => { const roles = new Reflector().get<RoleName[]>('roles', SubscriptionsController); assert.deepEqual(roles, [RoleName.SUPER_ADMIN]); const guard = new RolesGuard({ getAllAndOverride: () => roles } as never); const context = { getHandler: () => SubscriptionsController.prototype.findAll, getClass: () => SubscriptionsController, switchToHttp: () => ({ getRequest: () => ({ user: { ...actor, roles: [RoleName.COMPANY_ADMIN] } }) }) }; assert.throws(() => guard.canActivate(context as never), ForbiddenException); });
  it('snapshots plan commercial terms and audits creation', async () => { const h = createHarness(); await h.service.create(dto, actor); assert.equal(h.data().planCodeSnapshot, 'GROWTH'); assert.equal(h.data().pricePerSeatMinor, 9900); assert.deepEqual(h.data().entitlementsSnapshot, plan.entitlements); assert.deepEqual(h.audits, ['SUBSCRIPTION_CREATED']); });
  it('enforces company existence, active plan selection, and seat bounds', async () => { const missing = serviceWith({ company: { findFirst: async () => null }, plan: { findUnique: async () => plan } }); await assert.rejects(() => missing.create(dto, actor)); const inactive = createHarness({ ...plan, status: PlanStatus.INACTIVE }); await assert.rejects(() => inactive.service.create(dto, actor), BadRequestException); for (const seatQuantity of [1, 51]) await assert.rejects(() => createHarness().service.create({ ...dto, seatQuantity }, actor), BadRequestException); });
  it('rejects malformed periods, unknown limits, Coming Soon entitlements, and nulls without TypeError', async () => { await assert.rejects(() => createHarness().service.create({ ...dto, currentPeriodStart: new Date() }, actor), BadRequestException); const custom = { ...plan, code: 'CUSTOM', billingModel: PlanBillingModel.CUSTOM, monthlyPricePerSeatMinor: null }; await assert.rejects(() => createHarness(custom).service.create({ ...dto, customRecurringPriceMinor: 1000, entitlements: ['crm.core'] }, actor), BadRequestException); await assert.rejects(() => createHarness(custom).service.create({ ...dto, customRecurringPriceMinor: 1000, limits: { arbitrary: 1 } }, actor), BadRequestException); await assert.rejects(() => createHarness().service.create({ ...dto, seatQuantity: null } as never, actor), BadRequestException); });
  it('supports negotiated CUSTOM and complimentary zero pricing', async () => { const custom = { ...plan, code: 'CUSTOM', billingModel: PlanBillingModel.CUSTOM, monthlyPricePerSeatMinor: null }; const h = createHarness(custom); await h.service.create({ ...dto, activationSource: SubscriptionActivationSource.COMPLIMENTARY, entitlements: ['workforce.leave'] }, actor); assert.equal(h.data().customRecurringPriceMinor, 0); assert.deepEqual(h.data().entitlementsSnapshot, ['workforce.leave']); });
  it('activates, suspends, resumes, and cancels with focused audits', async () => { const activate = lifecycleHarness(); await activate.service.activate(subscription.id, {}, actor); assert.equal(activate.data().status, SubscriptionStatus.ACTIVE); assert.ok(activate.data().startsAt); const suspend = lifecycleHarness({ ...subscription, status: SubscriptionStatus.ACTIVE }); await suspend.service.suspend(subscription.id, actor); assert.equal(suspend.data().status, SubscriptionStatus.SUSPENDED); const resume = lifecycleHarness({ ...subscription, status: SubscriptionStatus.SUSPENDED }); await resume.service.resume(subscription.id, actor); assert.equal(resume.data().suspendedAt, null); const cancel = lifecycleHarness({ ...subscription, status: SubscriptionStatus.ACTIVE }); await cancel.service.cancel(subscription.id, actor); assert.equal(cancel.data().status, SubscriptionStatus.CANCELLED); });
  it('rejects invalid/no-op/terminal transitions and a second live subscription', async () => { await assert.rejects(() => lifecycleHarness({ ...subscription, status: SubscriptionStatus.ACTIVE }).service.activate(subscription.id, {}, actor), BadRequestException); await assert.rejects(() => lifecycleHarness({ ...subscription, status: SubscriptionStatus.CANCELLED }).service.activate(subscription.id, {}, actor), BadRequestException); await assert.rejects(() => lifecycleHarness(subscription, { id: 'other-live' }).service.activate(subscription.id, {}, actor), ConflictException); });
  it('expires only an ended fixed/current period and preserves snapshot fields', async () => { await assert.rejects(() => lifecycleHarness({ ...subscription, status: SubscriptionStatus.ACTIVE }).service.expire(subscription.id, actor), BadRequestException); const ended = lifecycleHarness({ ...subscription, status: SubscriptionStatus.ACTIVE, currentPeriodStart: new Date('2025-01-01'), currentPeriodEnd: new Date('2025-02-01') }); await ended.service.expire(subscription.id, actor); assert.equal(ended.data().status, SubscriptionStatus.EXPIRED); assert.equal(ended.data().planCodeSnapshot, undefined); });
  it('uses identical filtered where clauses for list rows and total', async () => { let rowWhere: unknown; let countWhere: unknown; const service = serviceWith({ companySubscription: { findMany: async ({ where }: { where: unknown }) => { rowWhere = where; return []; }, count: async ({ where }: { where: unknown }) => { countWhere = where; return 0; } }, $transaction: async (ops: Promise<unknown>[]) => Promise.all(ops) }); const result = await service.findAll({ page: 1, limit: 20, search: 'growth', status: SubscriptionStatus.ACTIVE, activationSource: SubscriptionActivationSource.MANUAL }); assert.deepEqual(rowWhere, countWhere); assert.equal(result.meta.total, 0); });
  it('amends ACTIVE atomically into an ACTIVE successor with lineage and audits', async () => { const h = amendmentHarness(); const result = await h.service.amend(subscription.id, { seatQuantity: 6 }, actor); assert.equal(result.status, SubscriptionStatus.ACTIVE); assert.equal(h.data().supersedesSubscriptionId, subscription.id); assert.deepEqual(Object.keys(h.sourceUpdate()).sort(), ['endedAt', 'status']); assert.equal(h.sourceUpdate().status, SubscriptionStatus.SUPERSEDED); assert.deepEqual(h.events, ['update:SUPERSEDED', 'create', 'audit:SUBSCRIPTION_SUPERSEDED', 'audit:SUBSCRIPTION_AMENDED']); assert.deepEqual(h.audits, ['SUBSCRIPTION_SUPERSEDED', 'SUBSCRIPTION_AMENDED']); });
  it('keeps a SUSPENDED amendment suspended and never resumes access', async () => { const suspendedAt = new Date('2026-01-01'); const h = amendmentHarness({ ...subscription, status: SubscriptionStatus.SUSPENDED, suspendedAt }); await h.service.amend(subscription.id, { seatQuantity: 6 }, actor); assert.equal(h.data().status, SubscriptionStatus.SUSPENDED); assert.equal(h.data().suspendedAt, suspendedAt); });
  it('carries unchanged snapshots from the source instead of a drifted live Plan', async () => { const drifted = { ...plan, name: 'Renamed Live Plan', monthlyPricePerSeatMinor: 50000, entitlements: ['workforce.leave'], limits: { screenshotRetentionDays: 90 } }; const h = amendmentHarness({ ...subscription, status: SubscriptionStatus.ACTIVE }, drifted); await h.service.amend(subscription.id, { billingInterval: BillingInterval.YEARLY }, actor); assert.equal(h.data().planNameSnapshot, subscription.planNameSnapshot); assert.equal(h.data().pricePerSeatMinor, subscription.pricePerSeatMinor); assert.deepEqual(h.data().entitlementsSnapshot, subscription.entitlementsSnapshot); assert.deepEqual(h.data().limitsSnapshot, subscription.limitsSnapshot); });
  it('snapshots an eligible target Plan when the amendment changes Plan', async () => { const target = { ...plan, id: 'plan-2', code: 'ENTERPRISE', name: 'Enterprise', monthlyPricePerSeatMinor: 19900, entitlements: ['workforce.leave'] }; const h = amendmentHarness({ ...subscription, status: SubscriptionStatus.ACTIVE }, target); await h.service.amend(subscription.id, { planId: target.id }, actor); assert.equal(h.data().planId, target.id); assert.equal(h.data().planCodeSnapshot, 'ENTERPRISE'); assert.equal(h.data().pricePerSeatMinor, 19900); assert.deepEqual(h.data().entitlementsSnapshot, ['workforce.leave']); });
  it('rejects semantic no-op amendments and every ineligible source status', async () => { await assert.rejects(() => amendmentHarness().service.amend(subscription.id, {}, actor), BadRequestException); for (const status of [SubscriptionStatus.PENDING, SubscriptionStatus.SUPERSEDED, SubscriptionStatus.CANCELLED, SubscriptionStatus.EXPIRED]) await assert.rejects(() => amendmentHarness({ ...subscription, status }).service.amend(subscription.id, { seatQuantity: 6 }, actor), BadRequestException); });
  it('does not allow SUPERSEDED to reactivate', async () => { await assert.rejects(() => lifecycleHarness({ ...subscription, status: SubscriptionStatus.SUPERSEDED }).service.activate(subscription.id, {}, actor), BadRequestException); });
  it('blocks activation, resume, and live amendment while an effective Trial exists', async () => { const trial = { id: 'trial-1' }; await assert.rejects(() => lifecycleHarness(subscription, null, trial).service.activate(subscription.id, {}, actor), ConflictException); await assert.rejects(() => lifecycleHarness({ ...subscription, status: SubscriptionStatus.SUSPENDED }, null, trial).service.resume(subscription.id, actor), ConflictException); await assert.rejects(() => amendmentHarness({ ...subscription, status: SubscriptionStatus.ACTIVE }, plan, false, trial).service.amend(subscription.id, { seatQuantity: 6 }, actor), ConflictException); });
  it('requires an explicit reasoned override to activate below current usage', async () => { const current = { ...subscription, seatQuantity: 3 }; const service = serviceWith({ $transaction: async (callback: (value: unknown) => unknown) => callback({ companySubscription: { findUnique: async () => current, findFirst: async () => null, update: async ({ data }: { data: Record<string, unknown> }) => ({ ...current, ...data }) }, companyTrial: { findFirst: async () => null }, auditLog: { create: async () => ({}) } }) }, 4); await assert.rejects(() => service.activate(current.id, {}, actor), BadRequestException); const result = await service.activate(current.id, { allowOverLimit: true, reason: 'Approved exception' }, actor); assert.equal(result.status, SubscriptionStatus.ACTIVE); });
  it('requires an explicit reasoned override to amend below current usage', async () => { const rejected = amendmentHarness({ ...subscription, status: SubscriptionStatus.ACTIVE }, plan, false, null, 6); await assert.rejects(() => rejected.service.amend(subscription.id, { seatQuantity: 4 }, actor), BadRequestException); assert.deepEqual(rejected.events, []); const approved = amendmentHarness({ ...subscription, status: SubscriptionStatus.ACTIVE }, plan, false, null, 6); const result = await approved.service.amend(subscription.id, { seatQuantity: 4, allowOverLimit: true, reason: 'Approved downgrade' }, actor); assert.equal(result.seatQuantity, 4); assert.deepEqual(approved.audits, ['SUBSCRIPTION_SUPERSEDED', 'SUBSCRIPTION_AMENDED']); });
  it('keeps source replacement and successor creation in one transaction so failures reject the operation', async () => { const h = amendmentHarness({ ...subscription, status: SubscriptionStatus.ACTIVE }, plan, true); await assert.rejects(() => h.service.amend(subscription.id, { seatQuantity: 6 }, actor), /create failed/); assert.deepEqual(h.events, ['update:SUPERSEDED', 'create']); assert.deepEqual(h.audits, []); });
  it('accepts SUPERSEDED in list status filtering', async () => { let where: { status?: SubscriptionStatus } = {}; const service = serviceWith({ companySubscription: { findMany: async (args: { where: typeof where }) => { where = args.where; return []; }, count: async () => 0 }, $transaction: async (ops: Promise<unknown>[]) => Promise.all(ops) }); await service.findAll({ page: 1, limit: 20, status: SubscriptionStatus.SUPERSEDED }); assert.equal(where.status, SubscriptionStatus.SUPERSEDED); });
});
