import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, useLocation, useNavigate } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { PlatformDunningFilterDraft } from '../components/PlatformDunningFilters';
const { list, filterProps, listProps } = vi.hoisted(() => ({ list: vi.fn(), filterProps: { current: null as Record<string, unknown> | null }, listProps: { current: null as Record<string, unknown> | null } }));
vi.mock('../platform-dunning-api', async original => ({ ...(await original<typeof import('../platform-dunning-api')>()), listPlatformDunning: list }));
vi.mock('../components/PlatformDunningFilters', () => ({ PlatformDunningFilters: (props: Record<string, unknown>) => { filterProps.current = props; return <div><span>Summary: {String(props.summary)}</span><button onClick={() => (props.onApply as () => void)()}>Apply mock</button><button onClick={() => (props.onClear as () => void)()}>Reset mock</button><button onClick={() => (props.onRefresh as () => void)()}>Refresh mock</button></div>; } }));
vi.mock('../components/PlatformDunningList', () => ({ PlatformDunningList: (props: Record<string, unknown>) => { listProps.current = props; return props.loading ? <div>Loading list</div> : <div>List ready: {(props.rows as Array<{ renewal: { id: string } }>).map(row => row.renewal.id).join(', ')}<button onClick={() => (props.onPaginationChange as (page: number, limit: number) => void)(2, 20)}>Next page mock</button></div>; } }));
import PlatformDunningPage from './PlatformDunningPage';
const empty = { data: { evaluationTime: '2026-01-01T00:00:00.000Z', data: [], meta: { page: 1, limit: 20, total: 0, totalPages: 0 } } };
describe('PlatformDunningPage', () => {
  beforeEach(() => { list.mockReset().mockResolvedValue(empty); filterProps.current = null; listProps.current = null; });
  it('normalizes defaults and announces initial loading', async () => { let resolve!: (value: unknown) => void; list.mockImplementation(() => new Promise(done => { resolve = done; })); renderPage(); expect(screen.getByRole('status')).toHaveTextContent('Loading Dunning register'); await waitFor(() => expect(list).toHaveBeenCalledWith({ page: 1, limit: 20 })); resolve(empty); await waitFor(() => expect(screen.queryByRole('status')).not.toBeInTheDocument()); expect(screen.getByTestId('location')).toHaveTextContent('?page=1&limit=20'); });
  it('keeps draft changes silent, then applies at page one', async () => { renderPage('/?page=3&limit=20&keep=yes'); await waitFor(() => expect(list).toHaveBeenCalledTimes(1)); act(() => (filterProps.current?.onChange as (draft: PlatformDunningFilterDraft) => void)({ ...(filterProps.current?.draft as PlatformDunningFilterDraft), paymentStatus: 'FAILED' })); expect(list).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByText('Apply mock')); await waitFor(() => expect(list).toHaveBeenLastCalledWith(expect.objectContaining({ page: 1, paymentStatus: 'FAILED' }))); expect(screen.getByTestId('location')).toHaveTextContent('keep=yes'); });
  it('resets filters, refreshes current query, and maps pagination', async () => { renderPage('/?page=2&limit=50&paymentStatus=FAILED'); await waitFor(() => expect(listProps.current).not.toBeNull()); fireEvent.click(screen.getByText('Refresh mock')); await waitFor(() => expect(list.mock.calls.length).toBeGreaterThan(1)); fireEvent.click(screen.getByText('Reset mock')); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 1, limit: 50 })); act(() => (listProps.current?.onPaginationChange as (page: number, limit: number) => void)(3, 50)); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 3, limit: 50 })); });
  it('uses authoritative metadata for the result count', async () => { list.mockResolvedValue({ data: { ...empty.data, meta: { page: 1, limit: 20, total: 37, totalPages: 2 } } }); renderPage(); expect(await screen.findByText('Summary: 37 open Dunning records')).toBeInTheDocument(); });
  it('keeps filters while user-driven server pagination updates URL and request', async () => { renderPage('/?page=1&limit=20&paymentStatus=AUTHORIZED&keep=yes'); await screen.findByText(/List ready:/); fireEvent.click(screen.getByText('Next page mock')); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 2, limit: 20, paymentStatus: 'AUTHORIZED' })); expect(screen.getByTestId('location')).toHaveTextContent('paymentStatus=AUTHORIZED'); expect(screen.getByTestId('location')).toHaveTextContent('keep=yes'); });
  it('rehydrates applied and draft filters across Back and Forward history', async () => { renderPage('/?page=1&limit=20&paymentStatus=PENDING'); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 1, limit: 20, paymentStatus: 'PENDING' })); act(() => (filterProps.current?.onChange as (draft: PlatformDunningFilterDraft) => void)({ ...(filterProps.current?.draft as PlatformDunningFilterDraft), paymentStatus: 'AUTHORIZED' })); fireEvent.click(screen.getByText('Apply mock')); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 1, limit: 20, paymentStatus: 'AUTHORIZED' })); fireEvent.click(screen.getByText('Back mock')); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 1, limit: 20, paymentStatus: 'PENDING' })); expect((filterProps.current?.draft as PlatformDunningFilterDraft).paymentStatus).toBe('PENDING'); fireEvent.click(screen.getByText('Forward mock')); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page: 1, limit: 20, paymentStatus: 'AUTHORIZED' })); expect((filterProps.current?.draft as PlatformDunningFilterDraft).paymentStatus).toBe('AUTHORIZED'); });
  it('retains rows, sanitizes background failure, and exposes Retry', async () => { let reject!: (error: unknown) => void; list.mockResolvedValueOnce({ data: { ...empty.data, data: [{ renewal: { id: 'renewal-1' } }], meta: { page: 1, limit: 20, total: 1, totalPages: 1 } } }).mockImplementationOnce(() => new Promise((_, fail) => { reject = fail; })); renderPage(); expect(await screen.findByText('List ready: renewal-1')).toBeInTheDocument(); fireEvent.click(screen.getByText('Refresh mock')); reject({ isAxiosError: true, response: { status: 500, data: { message: 'raw secret' } } }); expect(await screen.findByText(/Showing the most recent available data/)).toBeInTheDocument(); expect(screen.getByText('List ready: renewal-1')).toBeInTheDocument(); expect(screen.queryByText('raw secret')).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Retry' })).toBeInTheDocument(); });
  it.each([[400, 'filters are invalid'], [403, 'Access restricted'], [500, 'could not be loaded']])('renders a sanitized %s error and Retry', async (status, text) => { list.mockRejectedValue({ isAxiosError: true, response: { status, data: { message: 'secret' } } }); renderPage(); expect(await screen.findByText(new RegExp(text, 'i'))).toBeInTheDocument(); expect(screen.queryByText('secret')).not.toBeInTheDocument(); fireEvent.click(screen.getByText('Retry')); await waitFor(() => expect(list.mock.calls.length).toBeGreaterThan(1)); });
});
function renderPage(initial = '/') { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[initial]}><PlatformDunningPage /><Location /></MemoryRouter></QueryClientProvider>); }
function Location() { const location = useLocation(); const navigate = useNavigate(); return <><span data-testid="location">{location.pathname}{location.search}</span><button onClick={() => void navigate(-1)}>Back mock</button><button onClick={() => void navigate(1)}>Forward mock</button></>; }
