import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { PlatformDunningDetails } from '../platform-dunning.types';
const { get } = vi.hoisted(() => ({ get: vi.fn() }));
vi.mock('../platform-dunning-api', async original => ({ ...(await original<typeof import('../platform-dunning-api')>()), getPlatformDunning: get }));
import PlatformDunningDetailsPage from './PlatformDunningDetailsPage';

const detail: PlatformDunningDetails = {
  active: true, classification: 'OPEN', reason: 'PAYMENT_FAILED', evaluationTime: '2026-09-03T00:00:00.000Z', dueAt: '2026-09-01T00:00:00.000Z',
  renewal: { id: '11111111-1111-4111-8111-111111111111', status: 'PREPARED', cycleStart: '2026-09-01T00:00:00.000Z', cycleEnd: '2026-10-01T00:00:00.000Z', billingInterval: 'MONTHLY', createdAt: '2026-08-20T00:00:00.000Z', recurringPriceBasis: 'PER_USER_UNIT', recurringUnitPriceMinor: '9007199254740993', recurringTotalPriceMinor: '9007199254740993', currency: 'INR', seatQuantity: 10, applicationAttemptCount: 2, lastApplicationAttemptAt: '2026-09-02T00:00:00.000Z', appliedAt: null, blockedAt: null, blockCode: null, safeBlockMessage: null, preparedByUserId: null },
  company: { id: '22222222-2222-4222-8222-222222222222', name: 'Acme' },
  subscription: { id: '33333333-3333-4333-8333-333333333333', status: 'ACTIVE', plan: { id: '44444444-4444-4444-8444-444444444444', code: 'PRO', name: 'Pro' } },
  payment: { id: '55555555-5555-4555-8555-555555555555', purpose: 'SUBSCRIPTION_RENEWAL', status: 'FAILED', amountMinor: '9007199254740993', currency: 'INR', provider: 'RAZORPAY', mode: 'TEST', providerStatus: 'failed', failedAt: '2026-09-02T00:00:00.000Z', failureCode: 'SAFE_CODE', safeFailureMessage: 'Safe message', authorizedAt: null, capturedAt: null, createdAt: '2026-08-20T00:00:00.000Z', updatedAt: '2026-09-02T00:00:00.000Z' },
  latestProviderOrder: { id: '66666666-6666-4666-8666-666666666666', status: 'CLOSED', providerStatus: 'closed-safe', createdAt: '2026-08-20T00:00:00.000Z', updatedAt: '2026-09-02T00:00:00.000Z' },
  attempts: { data: [{ id: 'attempt-2', sequence: 2, operation: 'PROVIDER_FETCH', status: 'FAILED', providerStatus: 'failed', failureCode: 'SAFE', safeFailureMessage: 'Retryable evidence', startedAt: '2026-09-02T00:00:00.000Z', completedAt: '2026-09-02T00:01:00.000Z' }, { id: 'attempt-1', sequence: 1, operation: 'ORDER_CREATE', status: 'SUCCEEDED', providerStatus: 'created', failureCode: null, safeFailureMessage: null, startedAt: '2026-08-20T00:00:00.000Z', completedAt: '2026-08-20T00:01:00.000Z' }], truncated: true },
  tax: { treatment: 'TAXABLE', decisionAt: '2026-08-20T00:00:00.000Z', currency: 'INR', taxableSubtotalMinor: '9007199254740993', totalTaxMinor: '1800', grossTotalMinor: '9007199254742793', jurisdictionClassification: 'INTER_STATE', serviceClassification: '9983', components: [{ type: 'IGST', rateBasisPoints: 1800, taxableAmountMinor: '9007199254740993', taxAmountMinor: '1800', currency: 'INR' }] },
  invoice: { id: '77777777-7777-4777-8777-777777777777', invoiceNumber: 'INV-1', issuedAt: '2026-09-03T00:00:00.000Z', currency: 'INR', subtotalMinor: '9007199254740993', totalTaxMinor: '1800', totalMinor: '9007199254742793' },
};

describe('PlatformDunningDetailsPage', () => {
  beforeEach(() => { get.mockReset(); get.mockResolvedValue({ data: detail }); });
  it('loads one detail and renders authoritative evidence, exact money, and safe links', async () => { renderPage(); expect(screen.getByRole('status')).toHaveTextContent('Loading Dunning details'); expect(await screen.findByText('PAYMENT FAILED')).toBeInTheDocument(); expect(get).toHaveBeenCalledWith(detail.renewal.id); expect(screen.getByText('PER USER UNIT')).toBeInTheDocument(); expect(screen.getByText('TAXABLE')).toBeInTheDocument(); expect(screen.getAllByText('INR 90071992547409.93').length).toBeGreaterThan(0); for (const [name, href] of [['Acme', '/organization/companies/' + detail.company.id], ['Pro (PRO)', '/saas/subscriptions/' + detail.subscription.id], [detail.renewal.id, '/billing/renewals/' + detail.renewal.id], [detail.payment.id, '/billing/payments/' + detail.payment.id], ['INV-1', '/billing/invoices/' + detail.invoice!.id]]) expect(screen.getByRole('link', { name })).toHaveAttribute('href', href); });
  it.each(['NOT_DUE', 'RECOVERY_PENDING', 'RESOLVED', 'STOPPED'] as const)('renders %s without fabricating an OPEN reason', async classification => { get.mockResolvedValue({ data: { ...detail, active: false, classification, reason: null } }); renderPage(); expect(await screen.findByText(classification.replace('_', ' '))).toBeInTheDocument(); expect(screen.queryByText('PAYMENT FAILED')).not.toBeInTheDocument(); });
  it('keeps current CAPTURED truth stronger than retained failure evidence', async () => { get.mockResolvedValue({ data: { ...detail, classification: 'RECOVERY_PENDING', reason: null, payment: { ...detail.payment, status: 'CAPTURED', capturedAt: '2026-09-03T00:00:00.000Z' } } }); renderPage(); expect(await screen.findByText('CAPTURED')).toBeInTheDocument(); expect(screen.getByText(/currently CAPTURED/)).toBeInTheDocument(); expect(screen.getByText('Safe message')).toBeInTheDocument(); });
  it('renders provider, ordered bounded attempts, GST, Invoice and application evidence', async () => { renderPage(); expect(await screen.findByText('closed-safe')).toBeInTheDocument(); const attempts = screen.getByText('Attempt 2').closest('article')?.parentElement; expect(attempts).toBeTruthy(); expect(within(attempts!).getAllByRole('article')[0]).toHaveTextContent('Attempt 2'); expect(screen.getByRole('note')).toHaveTextContent('latest 25'); expect(screen.getByText('INTER STATE')).toBeInTheDocument(); expect(screen.getByText('Application attempts').parentElement).toHaveTextContent('2'); });
  it('renders every authoritative attempt operation/status and both commercial enum branches without overriding CAPTURED truth', async () => {
    const operations: PlatformDunningDetails['attempts']['data'][number]['operation'][] = ['ORDER_CREATE', 'CHECKOUT_CONFIRMATION', 'PROVIDER_PAYMENT', 'PROVIDER_FETCH', 'CAPTURE', 'WEBHOOK', 'RECONCILIATION'];
    const statuses: PlatformDunningDetails['attempts']['data'][number]['status'][] = ['PENDING', 'SUCCEEDED', 'FAILED', 'UNKNOWN'];
    get.mockResolvedValue({ data: { ...detail, renewal: { ...detail.renewal, recurringPriceBasis: 'FIXED_TOTAL' }, payment: { ...detail.payment, status: 'CAPTURED', capturedAt: '2026-09-03T00:00:00.000Z' }, attempts: { truncated: false, data: operations.map((operation, index) => ({ id: `attempt-${index}`, sequence: operations.length - index, operation, status: statuses[index % statuses.length], providerStatus: null, failureCode: null, safeFailureMessage: null, startedAt: '2026-09-02T00:00:00.000Z', completedAt: null })) } } });
    renderPage(); expect(await screen.findByText('FIXED TOTAL')).toBeInTheDocument(); for (const operation of operations) expect(screen.getByText(operation.replaceAll('_', ' '))).toBeInTheDocument(); for (const status of statuses) expect(screen.getAllByText(status).length).toBeGreaterThan(0); expect(screen.getByText('CAPTURED')).toBeInTheDocument(); expect(screen.getByText(/currently CAPTURED/)).toBeInTheDocument();
  });
  it('renders the authoritative NON_TAXABLE treatment without fabricating tax policy', async () => { get.mockResolvedValue({ data: { ...detail, tax: { ...detail.tax!, treatment: 'NON_TAXABLE' } } }); renderPage(); expect(await screen.findByText('NON TAXABLE')).toBeInTheDocument(); });
  it('handles absent provider, attempts, GST, Invoice, and failure evidence', async () => { get.mockResolvedValue({ data: { ...detail, latestProviderOrder: null, attempts: { data: [], truncated: false }, tax: null, invoice: null, payment: { ...detail.payment, failedAt: null, failureCode: null, safeFailureMessage: null } } }); renderPage(); expect(await screen.findByText('No provider order available.')).toBeInTheDocument(); expect(screen.getByText('No Payment attempts available.')).toBeInTheDocument(); expect(screen.getByText('No persisted tax evidence available.')).toBeInTheDocument(); expect(screen.getByText('No linked Invoice available.')).toBeInTheDocument(); expect(screen.getByText('No historical failure evidence available.')).toBeInTheDocument(); });
  it('shows blocked evidence without adding mutation controls', async () => { get.mockResolvedValue({ data: { ...detail, active: false, classification: 'STOPPED', reason: null, renewal: { ...detail.renewal, status: 'BLOCKED', blockedAt: '2026-09-03T00:00:00.000Z', blockCode: 'BLOCKED_SAFE', safeBlockMessage: 'Safe block' } } }); renderPage(); expect(await screen.findByText('BLOCKED_SAFE')).toBeInTheDocument(); expect(screen.getByText('Safe block')).toBeInTheDocument(); expect(screen.queryByRole('button', { name: /recover|charge|capture|mark paid|prepare|unblock/i })).not.toBeInTheDocument(); });
  it('renders direct APPLIED lifecycle evidence', async () => { get.mockResolvedValue({ data: { ...detail, active: false, classification: 'RESOLVED', reason: null, renewal: { ...detail.renewal, status: 'APPLIED', appliedAt: '2026-09-03T00:00:00.000Z', applicationAttemptCount: 3 } } }); renderPage(); expect(await screen.findByText('RESOLVED')).toBeInTheDocument(); expect(screen.getByText('Renewal status').parentElement).toHaveTextContent('APPLIED'); expect(screen.getByText('Application attempts').parentElement).toHaveTextContent('3'); expect(screen.getByText('Applied').parentElement).not.toHaveTextContent('Not available'); });
  it.each([[400, 'reference is invalid'], [403, 'Access restricted'], [404, 'Dunning record not found']] as const)('renders sanitized %s failure', async (status, message) => { get.mockRejectedValue(Object.assign(new Error('raw secret'), { isAxiosError: true, response: { status, data: { message: 'raw secret' } } })); renderPage(); expect(await screen.findByText(new RegExp(message, 'i'))).toBeInTheDocument(); expect(screen.queryByText('raw secret')).not.toBeInTheDocument(); });
  it('sanitizes a generic error and retries successfully', async () => { get.mockRejectedValueOnce(Object.assign(new Error('raw secret'), { isAxiosError: true, response: { status: 500, data: { message: 'raw secret' } } })).mockResolvedValueOnce({ data: detail }); renderPage(); expect(await screen.findByText(/could not be loaded/i)).toBeInTheDocument(); expect(screen.queryByText('raw secret')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Retry loading' })); expect(await screen.findByText('PAYMENT FAILED')).toBeInTheDocument(); expect(get).toHaveBeenCalledTimes(2); });
  it('retains detail after background failure with Retry', async () => { let reject!: (error: unknown) => void; get.mockResolvedValueOnce({ data: detail }).mockImplementationOnce(() => new Promise((_, fail) => { reject = fail; })); renderPage(); expect(await screen.findByText('PAYMENT FAILED')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Refresh detail' })); reject({ isAxiosError: true, response: { status: 500, data: { message: 'raw secret' } } }); expect(await screen.findByText(/Showing the most recent available evidence/)).toBeInTheDocument(); expect(screen.getByText('PAYMENT FAILED')).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Retry' })).toBeInTheDocument(); expect(screen.queryByText('raw secret')).not.toBeInTheDocument(); });
});

function renderPage() {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={['/billing/dunning/' + detail.renewal.id]}><Routes><Route path="/billing/dunning/:renewalId" element={<><PlatformDunningDetailsPage /><button onClick={() => void client.refetchQueries({ queryKey: ['platform-dunning', 'details', detail.renewal.id] })}>Refresh detail</button></>} /></Routes></MemoryRouter></QueryClientProvider>);
}
