import { render, screen, within } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import type { PlatformRenewal } from '../platform-renewals.types';
import { PlatformRenewalList } from './PlatformRenewalList';
const renewal: PlatformRenewal = { id: '11111111-1111-4111-8111-111111111111', status: 'BLOCKED', cycleStart: '2026-09-01T00:00:00.000Z', cycleEnd: '2026-10-01T00:00:00.000Z', billingInterval: 'MONTHLY', recurringPriceBasis: 'PER_USER_UNIT', recurringUnitPriceMinor: '9007199254740993', recurringTotalPriceMinor: '9007199254740993', currency: 'INR', seatQuantity: 1, company: { id: '22222222-2222-4222-8222-222222222222', name: 'Acme' }, subscription: { id: '33333333-3333-4333-8333-333333333333', status: 'ACTIVE', plan: { id: '44444444-4444-4444-8444-444444444444', code: 'PRO', name: 'Pro' } }, payment: { id: '55555555-5555-4555-8555-555555555555', purpose: 'SUBSCRIPTION_RENEWAL', status: 'CAPTURED', amountMinor: '9007199254740993', currency: 'INR', provider: 'RAZORPAY', mode: 'TEST', capturedAt: '2026-09-01T00:00:00.000Z' }, preparedBy: null, applicationAttemptCount: 1, lastApplicationAttemptAt: '2026-09-02T00:00:00.000Z', appliedAt: null, blockedAt: '2026-09-02T00:00:00.000Z', blockCode: 'SAFE_CODE', safeBlockMessage: 'Safe block explanation', createdAt: '2026-09-01T00:00:00.000Z', updatedAt: '2026-09-02T00:00:00.000Z' };
describe('PlatformRenewalList', () => {
  it.each(['renewal-desktop-list', 'renewal-mobile-list'])('renders required operational evidence in %s', (testId) => { renderList([renewal]); const view = within(screen.getByTestId(testId)); expect(view.getByText('MONTHLY')).toBeInTheDocument(); expect(view.getByText(/RAZORPAY/)).toBeInTheDocument(); expect(view.getByText(/TEST/)).toBeInTheDocument(); expect(view.getByText(new RegExp(`^${formatDate(renewal.createdAt)}$`))).toBeInTheDocument(); expect(view.getByText(new RegExp(`^Blocked ${formatDate(renewal.blockedAt!)}$`))).toBeInTheDocument(); expect(view.getByText('BLOCKED')).toBeInTheDocument(); expect(view.getByText('CAPTURED')).toBeInTheDocument(); expect(view.getByText('INR 90071992547409.93')).toBeInTheDocument(); expect(view.getByText('Safe block explanation')).toBeInTheDocument(); });
  it('keeps the desktop Subscription ID and Plan snapshot in the same row', () => { renderList([renewal]); const desktop = within(screen.getByTestId('renewal-desktop-list')); const row = desktop.getByRole('row', { name: /Pro \(PRO\)/ }); expect(within(row).getByLabelText(renewal.subscription.id)).toBeInTheDocument(); expect(within(row).getByText('Pro (PRO)')).toBeInTheDocument(); });
  it.each(['renewal-desktop-list', 'renewal-mobile-list'])('renders applied timing in %s', (testId) => { const appliedAt = '2026-09-03T00:00:00.000Z'; renderList([{ ...renewal, status: 'APPLIED', appliedAt, blockedAt: null, blockCode: null, safeBlockMessage: null }]); expect(within(screen.getByTestId(testId)).getByText(new RegExp(`^Applied ${formatDate(appliedAt)}$`))).toBeInTheDocument(); });
  it.each([[false, 'No Renewal records available.'], [true, 'No renewals match the applied filters.']] as const)('renders the correct empty state', (filtered, title) => { renderList([], filtered); expect(screen.getAllByText(title).length).toBeGreaterThan(0); });
  it('uses server pagination totals', () => { render(<PlatformRenewalList rows={[renewal]} total={101} page={2} limit={20} loading={false} filtered={false} onPaginationChange={vi.fn()} />); expect(screen.getAllByText(/21–40 of 101/).length).toBeGreaterThan(0); });
});
function renderList(rows: PlatformRenewal[], filtered = false) { return render(<PlatformRenewalList rows={rows} total={rows.length} page={1} limit={20} loading={false} filtered={filtered} onPaginationChange={vi.fn()} />); }
function formatDate(value: string) { return new Date(value).toLocaleString().replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
