import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { beforeEach, describe, expect, it, vi } from 'vitest';
const { prepare } = vi.hoisted(() => ({ prepare: vi.fn() }));
vi.mock('../platform-renewals-api', async original => ({ ...(await original<typeof import('../platform-renewals-api')>()), preparePlatformRenewal: prepare }));
import { PrepareRenewalDialog, prepareRenewalErrorMessage } from './PrepareRenewalDialog';
const id = '123e4567-e89b-42d3-a456-426614174000';
const response = { data: { renewalId: 'renewal-1', paymentId: 'payment-1', subscriptionId: id, cycleStart: '2026-01-01T00:00:00.000Z', cycleEnd: '2026-02-01T00:00:00.000Z', created: true } };

describe('PrepareRenewalDialog', () => {
  beforeEach(() => { prepare.mockReset(); });
  it('validates the Subscription UUID locally without inventing eligibility rules', () => { renderDialog(); fireEvent.click(screen.getByRole('button', { name: 'Prepare Renewal' })); expect(screen.getByLabelText(/Subscription ID/)).toHaveAccessibleDescription('Subscription ID is required.'); fireEvent.change(screen.getByLabelText(/Subscription ID/), { target: { value: 'bad' } }); fireEvent.click(screen.getByRole('button', { name: 'Prepare Renewal' })); expect(screen.getByLabelText(/Subscription ID/)).toHaveAccessibleDescription('Enter a valid Subscription UUID.'); expect(prepare).not.toHaveBeenCalled(); });
  it.each([[true, true], [false, false]])('submits once, invalidates affected lists, and preserves the created=%s outcome', async (created, expected) => { prepare.mockResolvedValue({ data: { ...response.data, created } }); const h = renderDialog(); const invalidate = vi.spyOn(h.client, 'invalidateQueries'); fireEvent.change(screen.getByLabelText(/Subscription ID/), { target: { value: ` ${id} ` } }); fireEvent.click(screen.getByRole('button', { name: 'Prepare Renewal' })); await waitFor(() => expect(prepare).toHaveBeenCalledTimes(1)); await waitFor(() => expect(invalidate).toHaveBeenCalledWith({ queryKey: ['platform-renewals', 'list'] })); expect(invalidate).toHaveBeenCalledWith({ queryKey: ['platform-payments'] }); expect(h.onPrepared).toHaveBeenCalledWith('renewal-1', expected); });
  it('prevents duplicate submission while preparation is pending', async () => { let resolve!: (value: typeof response) => void; prepare.mockImplementation(() => new Promise(done => { resolve = done; })); const h = renderDialog(); fireEvent.change(screen.getByLabelText(/Subscription ID/), { target: { value: id } }); fireEvent.click(screen.getByRole('button', { name: 'Prepare Renewal' })); expect(await screen.findByRole('status')).toHaveTextContent('Preparing Renewal'); const dialog = screen.getByRole('dialog'); expect(screen.getByLabelText(/Subscription ID/)).toBeDisabled(); expect(screen.getByRole('button', { name: /Preparing/ })).toBeDisabled(); fireEvent.submit(dialog.querySelector('form')!); expect(prepare).toHaveBeenCalledTimes(1); resolve(response); await waitFor(() => expect(h.onPrepared).toHaveBeenCalledWith('renewal-1', true)); });
  it('associates its explanation and does not imply charge, capture, or renewal completion', () => { renderDialog(); const dialog = screen.getByRole('dialog'); expect(dialog).toHaveAttribute('aria-describedby', 'prepare-renewal-description'); expect(document.getElementById('prepare-renewal-description')).toHaveTextContent('backend determines eligibility'); expect(dialog).not.toHaveTextContent(/Charge Now|Auto Charge|Payment Captured|Subscription Renewed/i); });
  it.each([[404, 'Subscription was not found'], [409, 'not currently eligible'], [422, 'commercial snapshot is incomplete'], [500, 'Check connectivity']])('sanitizes HTTP %s errors', (status, text) => { const message = prepareRenewalErrorMessage(axiosError(status, { message: 'RAW SECRET' })); expect(message).toMatch(new RegExp(text, 'i')); expect(message).not.toContain('RAW SECRET'); });
  it('warns that durable evidence may exist after provider preparation failure', () => { expect(prepareRenewalErrorMessage(axiosError(409, { code: 'PROVIDER_PREPARATION_FAILED', message: 'RAW' }))).toMatch(/may already be durably prepared/i); });
});
function renderDialog() { const client = new QueryClient({ defaultOptions: { mutations: { retry: false } } }); const onClose = vi.fn(), onPrepared = vi.fn(); render(<QueryClientProvider client={client}><PrepareRenewalDialog open onClose={onClose} onPrepared={onPrepared} /></QueryClientProvider>); return { client, onClose, onPrepared }; }
function axiosError(status: number, data: object) { return Object.assign(new Error('request failed'), { isAxiosError: true, response: { status, data } }); }
